"""Digest drafts against a real migrated database.

Runs the phase 9 pipeline the way production does: the probe path records
and detects interleaved, the real outbox processor drains the freeze, the
dataset refresh, AND the digest social draft event it enqueues; the weekly
newsletter is generated by the beat's exact code path; and every row lands
in ``digest_drafts`` with status ``draft`` - the pipeline ends there.
"""

from datetime import datetime, timedelta, timezone

import pytest


def _ts(minutes_ago: int) -> datetime:
    return datetime.now(timezone.utc) - timedelta(minutes=minutes_ago)


async def _seed(db_session):
    from sqlalchemy import select

    from app.modules.vendors.models import VendorEndpoint, VendorTracking
    from app.modules.vendors.service import vendor_service

    await vendor_service.seed_vendors(db_session)
    await db_session.commit()
    vendor = (
        await db_session.execute(
            select(VendorTracking).where(VendorTracking.vendor_name == "stripe")
        )
    ).scalar_one()
    endpoint = (
        await db_session.execute(
            select(VendorEndpoint).where(VendorEndpoint.vendor_id == vendor.id)
        )
    ).scalars().first()
    return vendor, endpoint


async def _record(db_session, endpoint, minutes_ago: int, *, ok: bool, status: int):
    from app.modules.observations.schemas import ObservationCreateDTO
    from app.modules.observations.service import observation_service

    return await observation_service.record_observation(
        db_session,
        ObservationCreateDTO(
            timestamp=_ts(minutes_ago),
            source_type="vendor_probe",
            source_id=endpoint.id,
            region="us-east",
            endpoint_url=endpoint.endpoint_url,
            latency_ms=120.0 if ok else 0.0,
            status_code=status,
            error_type=None if ok else "probe_failed",
            error_message=None if ok else "HTTP failure",
            metadata={"is_up": ok},
        ),
    )


async def _apply(db_session, endpoint, vendor, observation):
    from app.modules.incidents.public_service import public_incident_service

    return await public_incident_service.apply_vendor_observation(
        db_session,
        endpoint=endpoint,
        vendor=vendor,
        observation=observation,
        region="us-east",
    )


async def _drain(db_session) -> int:
    from app.modules.observations.outbox import process_outbox_batch

    total = 0
    # A drain can enqueue follow-ups (freeze -> dataset refresh + social
    # draft); keep draining until the queue is empty so the test is not
    # coupled to batch scheduling.
    while True:
        processed = await process_outbox_batch(db_session, limit=100)
        await db_session.commit()
        total += processed
        if processed == 0:
            return total


async def _open_incident(db_session):
    vendor, endpoint = await _seed(db_session)
    ok0 = await _record(db_session, endpoint, 30, ok=True, status=200)
    await db_session.commit()
    assert await _apply(db_session, endpoint, vendor, ok0) is None
    fail1 = await _record(db_session, endpoint, 20, ok=False, status=503)
    await db_session.commit()
    assert await _apply(db_session, endpoint, vendor, fail1) is None
    fail2 = await _record(db_session, endpoint, 15, ok=False, status=503)
    await db_session.commit()
    opened = await _apply(db_session, endpoint, vendor, fail2)
    await db_session.commit()
    assert opened is not None
    return opened


@pytest.mark.asyncio
async def test_outbox_freeze_drafts_social_and_beat_drafts_newsletter(
    async_client, db_session
):
    from sqlalchemy import func, select

    from app.modules.digest.models import (
        KIND_INCIDENT_SOCIAL,
        KIND_WEEKLY_DIGEST,
        DigestDraft,
    )
    from app.modules.digest.service import digest_draft_service, week_window

    opened = await _open_incident(db_session)
    await _drain(db_session)

    # The freeze's outbox fast path drafted the social post - status draft,
    # no subject, no html, provenance attached.
    socials = (
        await db_session.execute(
            select(DigestDraft).where(DigestDraft.kind == KIND_INCIDENT_SOCIAL)
        )
    ).scalars().all()
    assert len(socials) == 1
    social = socials[0]
    assert social.status == "draft"
    assert social.subject is None
    assert social.html_body is None
    assert social.period_key == str(opened.id)
    assert social.incident_ids == [str(opened.id)]
    assert social.vendor_slugs == ["stripe"]
    assert "Status: open." in social.text_body
    assert f"/observatory/stripe/incidents/{opened.id}" in social.text_body
    assert social.content_hash

    # The beat's exact path drafts the weekly newsletter for the incident's
    # week (the monday..sunday window containing today).
    today = datetime.now(timezone.utc).date()
    period_start, period_end = week_window(today)
    from app.config import settings

    counts = await digest_draft_service.generate_pending(
        db_session, period_start, period_end, site_url=settings.SITE_URL
    )
    await db_session.commit()
    assert counts[f"{KIND_WEEKLY_DIGEST}_drafted"] == 1
    assert counts[f"{KIND_INCIDENT_SOCIAL}_drafted"] == 0, (
        "the social draft already exists from the outbox fast path"
    )

    newsletter = (
        await db_session.execute(
            select(DigestDraft).where(DigestDraft.kind == KIND_WEEKLY_DIGEST)
        )
    ).scalars().one()
    assert newsletter.status == "draft"
    assert "1 confirmed incident" in newsletter.subject
    assert str(opened.id) in newsletter.incident_ids
    assert "consecutive failed probes" in newsletter.text_body
    assert newsletter.html_body is not None

    # A second beat run is fully idempotent: nothing new.
    counts2 = await digest_draft_service.generate_pending(
        db_session, period_start, period_end, site_url=settings.SITE_URL
    )
    await db_session.commit()
    assert counts2 == {
        f"{KIND_WEEKLY_DIGEST}_drafted": 0,
        f"{KIND_INCIDENT_SOCIAL}_drafted": 0,
    }
    total = (
        await db_session.execute(select(func.count(DigestDraft.id)))
    ).scalar()
    assert total == 2


@pytest.mark.asyncio
async def test_resolution_freeze_versions_the_social_draft(async_client, db_session):
    from sqlalchemy import select

    from app.modules.digest.models import KIND_INCIDENT_SOCIAL, DigestDraft

    opened = await _open_incident(db_session)
    await _drain(db_session)

    # Resolve the incident; the resolution freeze rides the outbox too.
    vendor, endpoint = await _seed(db_session)
    ok1 = await _record(db_session, endpoint, 10, ok=True, status=200)
    await db_session.commit()
    assert await _apply(db_session, endpoint, vendor, ok1) is None
    ok2 = await _record(db_session, endpoint, 5, ok=True, status=200)
    await db_session.commit()
    resolved = await _apply(db_session, endpoint, vendor, ok2)
    await db_session.commit()
    assert resolved is not None

    await _drain(db_session)

    # Append-only versioning: the open draft AND the resolved draft both
    # exist; the newest says resolved.
    socials = (
        await db_session.execute(
            select(DigestDraft)
            .where(DigestDraft.kind == KIND_INCIDENT_SOCIAL)
            .order_by(DigestDraft.created_at.asc())
        )
    ).scalars().all()
    assert len(socials) == 2
    assert "Status: open." in socials[0].text_body
    assert "Status: resolved." in socials[1].text_body
    assert socials[0].content_hash != socials[1].content_hash
    # Both summarize the same incident.
    assert [d.incident_ids for d in socials] == [[str(opened.id)]] * 2


@pytest.mark.asyncio
async def test_admin_surface_lists_and_generates(async_client, db_session):

    from tests.helpers import make_admin_headers

    headers = await make_admin_headers(db_session)

    # Generate via the admin trigger (the beat's exact code path) on an
    # empty week: the explicit "no confirmed incidents" issue.
    resp = await async_client.post(
        "/v1/admin/digest/generate", json={"weeks_ago": 2}, headers=headers
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["counts"]["weekly_digest_drafted"] == 1

    # Non-admins are rejected before anything else.
    resp = await async_client.post("/v1/admin/digest/generate", json={})
    assert resp.status_code in (401, 403)

    # The drafts list shows the newsletter row; the reviewer reads exactly
    # what was generated.
    resp = await async_client.get("/v1/admin/digest/drafts", headers=headers)
    assert resp.status_code == 200
    items = resp.json()["items"]
    assert len(items) == 1
    draft = items[0]
    assert draft["status"] == "draft"
    assert "no confirmed incidents" in draft["subject"]
    assert "No confirmed incidents were recorded in this window" in draft["text_body"]

    # Kind filter works and detail resolves.
    resp = await async_client.get(
        "/v1/admin/digest/drafts", params={"kind": "incident_social"},
        headers=headers,
    )
    assert resp.json()["items"] == []

    draft_id = items[0]["id"]
    resp = await async_client.get(
        f"/v1/admin/digest/drafts/{draft_id}", headers=headers
    )
    assert resp.status_code == 200
    assert resp.json()["content_hash"] == draft["content_hash"]

    resp = await async_client.get(
        f"/v1/admin/digest/drafts/{'0' * 8}-0000-0000-0000-000000000000",
        headers=headers,
    )
    assert resp.status_code == 404

    # There is no send/post endpoint on this surface, by design: the
    # mounted router exposes exactly list + detail + generate.
    from app.bootstrap.routers import ROUTER_REGISTRY

    entry = next(e for e in ROUTER_REGISTRY if e.name == "digest_admin")
    assert entry.mounted
    digest_paths = sorted({getattr(r, "path", "") for r in entry.router.routes})
    assert digest_paths == [
        "/v1/admin/digest/drafts",
        "/v1/admin/digest/drafts/{draft_id}",
        "/v1/admin/digest/generate",
    ]
    methods = sorted(
        {m for r in entry.router.routes for m in (getattr(r, "methods", None) or set())}
    )
    assert methods == ["GET", "POST"]
