"""app.infrastructure.celery_app — backward-compatibility alias.

Canonical home: ``app.platform.messaging.celery_app``
Moved during the platform redesign. New code must import from the canonical
path; this module re-exports the exact same objects and is covered by the
import-parity test (``tests/unit/test_import_parity.py``).
"""

from app.platform.messaging.celery_app import (  # noqa: F401
    Celery,
    Queue,
    admin,
    agencies,
    ai_integration,
    api_keys,
    attribution,
    auth,
    badges,
    beat_task_names,
    billing,
    celery_app,
    checks,
    configure_logging,
    crontab,
    dashboard,
    dependencies,
    evidence,
    evidence_gate,
    incidents,
    logger,
    logging,
    notifications,
    observations,
    organizations,
    outreach,
    partners,
    probe_broker,
    referrals,
    settings,
    status_pages,
    task_failure,
    task_postrun,
    task_prerun,
    timeline_share,
    users,
    vendor_submissions,
    vendors,
    webhooks,
    worker_process_init,
)

__all__ = [
    "Celery",
    "Queue",
    "admin",
    "agencies",
    "ai_integration",
    "api_keys",
    "attribution",
    "auth",
    "badges",
    "beat_task_names",
    "billing",
    "celery_app",
    "checks",
    "configure_logging",
    "crontab",
    "dashboard",
    "dependencies",
    "evidence",
    "evidence_gate",
    "incidents",
    "logger",
    "logging",
    "notifications",
    "observations",
    "organizations",
    "outreach",
    "partners",
    "probe_broker",
    "referrals",
    "settings",
    "status_pages",
    "task_failure",
    "task_postrun",
    "task_prerun",
    "timeline_share",
    "users",
    "vendor_submissions",
    "vendors",
    "webhooks",
    "worker_process_init",

]
