'use client';

import { useQuery } from '@tanstack/react-query';
import { Activity, Boxes, ChartNoAxesCombined, CircleAlert, Gauge, RadioTower, UsersRound } from 'lucide-react';
import { adminApi } from '@/lib/admin-api';
import { formatCompactNumber, formatPercent, formatRatioPercent, humanize } from '@/lib/admin-utils';
import { cn } from '@/lib/utils';
import {
  AdminCard,
  AdminEmptyState,
  AdminPageHeader,
  DateRangeControl,
  MetricCard,
  SectionFailure,
  SectionHeading,
  SectionSkeleton,
} from '@/components/admin/admin-primitives';

export function ProductPage() {
  const overviewQuery = useQuery({ queryKey: ['admin', 'product', 'overview'], queryFn: adminApi.productOverview, staleTime: 90_000 });
  const featuresQuery = useQuery({ queryKey: ['admin', 'product', 'features'], queryFn: adminApi.productFeatures, staleTime: 120_000 });
  const vendorsQuery = useQuery({ queryKey: ['admin', 'product', 'vendors', 12], queryFn: () => adminApi.productVendors(12), staleTime: 120_000 });
  const engagementQuery = useQuery({ queryKey: ['admin', 'product', 'engagement'], queryFn: adminApi.productEngagement, staleTime: 90_000 });
  const activationQuery = useQuery({ queryKey: ['admin', 'product', 'activation'], queryFn: adminApi.productActivation, staleTime: 120_000 });

  return (
    <div className="space-y-6">
      <AdminPageHeader eyebrow="Product" title="Product health" description="See whether customers are actually getting RELIASTRA into production — without turning the page into a wall of metrics." actions={<DateRangeControl className="md:hidden" />} />
      {overviewQuery.isLoading && <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Array.from({ length: 5 }, (_, index) => <div key={index} className="h-36 animate-pulse rounded-xl border border-slate-200 bg-white dark:border-white/10 dark:bg-card" />)}</div>}
      {overviewQuery.isError && <AdminCard><SectionFailure title="Product overview unavailable." description="Product health metrics could not be loaded." onRetry={() => overviewQuery.refetch()} /></AdminCard>}
      {overviewQuery.data && <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Active organizations" value={formatCompactNumber(overviewQuery.data.active_organizations)} context="current activity" icon={UsersRound} /><MetricCard label="Active monitors" value={formatCompactNumber(overviewQuery.data.active_monitors)} context="monitoring configured" icon={RadioTower} /><MetricCard label="Dependencies" value={formatCompactNumber(overviewQuery.data.dependencies)} context="tracked services" icon={Boxes} /><MetricCard label="Checks today" value={formatCompactNumber(overviewQuery.data.checks_today)} context="executed signals" icon={Activity} /><MetricCard label="Open incidents" value={formatCompactNumber(overviewQuery.data.open_incidents)} context="requires review" icon={CircleAlert} tone={overviewQuery.data.open_incidents > 0 ? 'attention' : 'default'} /></section>}
      <section className="grid gap-5 xl:grid-cols-[1.05fr_0.95fr]"><FeatureAdoption query={featuresQuery} /><Engagement query={engagementQuery} activationQuery={activationQuery} /></section>
      <VendorCoverage query={vendorsQuery} />
    </div>
  );
}

function FeatureAdoption({ query }: { query: { isLoading: boolean; isError: boolean; data?: Awaited<ReturnType<typeof adminApi.productFeatures>>; refetch: () => unknown } }) {
  return <AdminCard><SectionHeading title="Feature adoption" subtitle="Which core value paths customers have actually adopted" /><div className="border-t border-slate-100 dark:border-white/10">{query.isLoading && <SectionSkeleton lines={6} />}{query.isError && <SectionFailure title="Feature adoption unavailable." description="Try refreshing this section." onRetry={() => query.refetch()} />}{query.data && query.data.features.length === 0 && <AdminEmptyState title="No feature adoption data yet." description="Adoption will appear as organizations begin using core RELIASTRA capabilities." icon={ChartNoAxesCombined} />}{query.data && query.data.features.length > 0 && <div className="divide-y divide-slate-100 dark:divide-white/10">{query.data.features.map((feature) => <div key={feature.feature} className="px-5 py-4 sm:px-6"><div className="flex items-baseline justify-between gap-4"><p className="text-sm font-medium text-slate-800 dark:text-slate-100">{humanize(feature.feature)}</p><p className="text-sm font-semibold tabular-nums text-slate-900 dark:text-white">{formatRatioPercent(feature.adoption_rate)}</p></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.max(0, Math.min(100, feature.adoption_rate * 100))}%` }} /></div><p className="mt-2 text-xs text-slate-500 dark:text-slate-400">{formatCompactNumber(feature.adopted)} of {formatCompactNumber(feature.eligible)} eligible organizations</p></div>)}</div>}</div></AdminCard>;
}

function Engagement({ query, activationQuery }: { query: { isLoading: boolean; isError: boolean; data?: Awaited<ReturnType<typeof adminApi.productEngagement>>; refetch: () => unknown }; activationQuery: { isLoading: boolean; isError: boolean; data?: Awaited<ReturnType<typeof adminApi.productActivation>>; refetch: () => unknown } }) {
  return <AdminCard><SectionHeading title="Engagement and activation" subtitle="Is usage becoming a habit, and how quickly does value begin?" /><div className="border-t border-slate-100 dark:border-white/10">{query.isLoading && <SectionSkeleton lines={5} />}{query.isError && <SectionFailure title="Engagement unavailable." description="Try refreshing this section." onRetry={() => query.refetch()} />}{query.data && <div className="grid sm:grid-cols-3">{[['DAU', query.data.dau], ['WAU', query.data.wau], ['MAU', query.data.mau]].map(([label, value], index) => <div key={label as string} className={cn('p-5', index < 2 && 'border-b border-slate-100 sm:border-b-0 sm:border-r dark:border-white/10')}><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">{label as string}</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em] tabular-nums text-slate-900 dark:text-white">{formatCompactNumber(value as number)}</p></div>)}</div>}{query.data && <div className="border-t border-slate-100 bg-slate-50/60 px-5 py-4 dark:border-white/10 dark:bg-white/[0.02] sm:px-6"><p className="text-xs text-slate-500 dark:text-slate-400">Stickiness <strong className="ml-1 font-semibold tabular-nums text-slate-800 dark:text-slate-100">{formatRatioPercent(query.data.stickiness)}</strong> DAU / MAU</p></div>}{activationQuery.isLoading && <SectionSkeleton lines={3} />}{activationQuery.isError && <SectionFailure title="Activation metric unavailable." description="Try refreshing this section." onRetry={() => activationQuery.refetch()} compact />}{activationQuery.data && <div className="border-t border-slate-100 px-5 py-5 dark:border-white/10 sm:px-6"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">Activation rate</p><p className="mt-2 text-2xl font-semibold tabular-nums text-slate-900 dark:text-white">{formatRatioPercent(activationQuery.data.activation_rate)}</p></div><div className="text-right"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">Median to first check</p><p className="mt-2 text-sm font-semibold tabular-nums text-slate-800 dark:text-slate-100">{activationQuery.data.median_time_to_first_check_hours === null || activationQuery.data.median_time_to_first_check_hours === undefined ? '—' : `${activationQuery.data.median_time_to_first_check_hours.toFixed(1)}h`}</p></div></div></div>}</div></AdminCard>;
}

function VendorCoverage({ query }: { query: { isLoading: boolean; isError: boolean; data?: Awaited<ReturnType<typeof adminApi.productVendors>>; refetch: () => unknown } }) {
  return <AdminCard><SectionHeading title="Vendor coverage" subtitle="The external services customers are monitoring, and how broadly they are covered" /><div className="border-t border-slate-100 dark:border-white/10">{query.isLoading && <SectionSkeleton lines={8} />}{query.isError && <SectionFailure title="Vendor coverage unavailable." description="Try refreshing this section." onRetry={() => query.refetch()} />}{query.data && query.data.vendors.length === 0 && <AdminEmptyState title="No vendor coverage data yet." description="Coverage appears after organizations add dependencies to monitor." icon={RadioTower} />}{query.data && query.data.vendors.length > 0 && <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/60 dark:border-white/10 dark:bg-white/[0.02]">{['Vendor', 'Organizations', 'Coverage', 'Monitoring', 'Incidents'].map((heading) => <th key={heading} className="px-5 py-2.5 text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">{heading}</th>)}</tr></thead><tbody>{query.data.vendors.map((vendor) => <tr key={vendor.vendor} className="border-b border-slate-100 last:border-0 dark:border-white/10"><td className="px-5 py-4 text-sm font-medium text-slate-800 dark:text-slate-100">{vendor.vendor}</td><td className="px-5 py-4 text-sm tabular-nums text-slate-600 dark:text-slate-300">{formatCompactNumber(vendor.organizations_using)}</td><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="h-1.5 w-24 overflow-hidden rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.max(0, Math.min(100, vendor.coverage_percentage))}%` }} /></div><span className="text-xs tabular-nums text-slate-500 dark:text-slate-400">{formatPercent(vendor.coverage_percentage)}</span></div></td><td className="px-5 py-4 text-sm tabular-nums text-slate-600 dark:text-slate-300">{formatCompactNumber(vendor.monitoring_volume)}</td><td className={cn('px-5 py-4 text-sm font-medium tabular-nums', vendor.incidents > 0 ? 'text-rose-700 dark:text-rose-400' : 'text-slate-600 dark:text-slate-300')}>{formatCompactNumber(vendor.incidents)}</td></tr>)}</tbody></table></div>}</div></AdminCard>;
}
