"""Paystack integration: HTTP client, payload helpers, and module singletons.

Owns the pooled ``httpx`` client, the ``PaystackClient`` API wrapper
(initialize / verify / fetch-plan), and the pure helpers that shape Paystack
payloads (amounts, metadata, timestamps, billing intervals). Other billing
modules import these; nothing here imports them back.
"""

import json
import logging
import uuid
from calendar import monthrange
from datetime import datetime
from typing import Any

import httpx

from app.config import settings
from app.core.exceptions import (
    ValidationException,
)
from app.modules.billing.channels import (
    checkout_channels,
)
from app.modules.billing.pricing import (
    ANNUAL as ANNUAL_INTERVAL,
)
from app.modules.billing.pricing import (
    payment_currency,
)
from app.modules.billing.schemas import (
    BillingInterval,
)
from app.platform.commercial.entitlements import (
    Plan,
    normalize_plan,
)

logger = logging.getLogger(__name__)



# P3 fix: pooled HTTP client for Paystack (like checks service) - one pool
# instead of a fresh TCP/TLS handshake per initialize/verify. Timeouts stay
# per-request via the client's default timeout.
_paystack_http_client: httpx.AsyncClient | None = None


def _get_paystack_http_client() -> httpx.AsyncClient:
    """Pooled Paystack client (factory-owned pool, module-global mirror)."""
    global _paystack_http_client
    from app.platform.integrations.http import get_shared_client

    _paystack_http_client = get_shared_client(
        "paystack",
        limits=httpx.Limits(max_connections=20, max_keepalive_connections=5),
        timeout=httpx.Timeout(10.0),
    )
    return _paystack_http_client


async def close_paystack_http_client() -> None:
    global _paystack_http_client
    from app.platform.integrations.http import aclose_shared_client

    await aclose_shared_client("paystack")
    _paystack_http_client = None


class PaystackClient:
    """Small async Paystack client built on the project's existing HTTP stack."""

    def __init__(self) -> None:
        self.base_url = settings.PAYSTACK_BASE_URL.rstrip("/")
        self.secret_key = settings.PAYSTACK_SECRET_KEY

    def _headers(self) -> dict[str, str]:
        if not self.secret_key:
            raise ValidationException("Paystack is not configured")
        return {
            "Authorization": f"Bearer {self.secret_key}",
            "Content-Type": "application/json",
        }

    async def initialize_transaction(
        self,
        email: str,
        amount: int,
        plan: str,
        metadata: dict[str, str] | None = None,
        currency: str | None = None,
        callback_url: str | None = None,
        channels: list[str] | None = None,
        reference: str | None = None,
    ) -> dict[str, Any]:
        """Create a Paystack transaction for exactly ``amount`` minor units.

        Two parameters here are load-bearing and were not obvious:

        * ``channels`` is always sent. Without it Paystack shows whatever the
          dashboard has ticked, which on a Nigerian merchant account means
          USSD, Pay with Bank and QR appear in front of a customer in
          Germany. RELIASTRA declares its own set
          (:mod:`app.modules.billing.channels`) so the checkout stays card-only
          regardless of what the dashboard is later changed to.
        * the ``plan`` field is *not* sent. Paystack's Initialize Transaction
          reference defines it as the code of a predefined Paystack plan
          (``PLN_...``) and states that supplying it "would invalidate the
          value provided in ``amount``". RELIASTRA's plans are priced by
          :mod:`app.modules.billing.pricing`, not by Paystack plan objects, so the
          plan name travels in ``metadata`` for reconciliation instead -
          sending ``"pro"`` there would either fail initialization or let the
          dashboard plan silently reprice the transaction.

        ``reference`` is generated by RELIASTRA rather than left to Paystack so
        the string itself carries the organization and can be correlated in
        logs, and so an initialization can be re-attempted for the same
        pending checkout without creating a second orphan transaction.
        """
        client = _get_paystack_http_client()
        payload: dict[str, Any] = {
            "email": email,
            "amount": amount,
            # Currency MUST be explicit: without it Paystack charges in
            # the merchant account's default currency, silently
            # repricing the plan. The caller passes the currency that
            # this amount was resolved in (payment_pricing), never a
            # separately-read setting, so the amount and its currency
            # can never drift apart.
            "currency": (currency or payment_currency()),
            "channels": channels or checkout_channels(),
            "metadata": metadata or {},
        }
        if reference:
            payload["reference"] = reference
        if callback_url:
            # Bring the customer back to RELIASTRA's checkout so the exact
            # charge is confirmed there (see the ?reference= handler in the
            # checkout page) instead of on a blank provider page.
            payload["callback_url"] = callback_url
        response = await client.post(
            f"{self.base_url}/transaction/initialize",
            headers=self._headers(),
            json=payload,
        )
        response.raise_for_status()
        return response.json()

    async def verify_transaction(self, reference: str) -> dict[str, Any]:
        client = _get_paystack_http_client()
        response = await client.get(
            f"{self.base_url}/transaction/verify/{reference}",
            headers=self._headers(),
        )
        response.raise_for_status()
        return response.json()

    async def fetch_plan(self, plan_code_or_id: str) -> dict[str, Any] | None:
        client = _get_paystack_http_client()
        response = await client.get(
            f"{self.base_url}/plan/{plan_code_or_id}",
            headers=self._headers(),
        )
        if response.status_code == 404:
            return None
        response.raise_for_status()
        return response.json()



paystack_client = PaystackClient()


def _add_calendar_months(moment: datetime, months: int) -> datetime:
    """Same day-of-month ``months`` later, clamped to shorter months."""
    year = moment.year + (moment.month - 1 + months) // 12
    month = (moment.month - 1 + months) % 12 + 1
    day = min(moment.day, monthrange(year, month)[1])
    return moment.replace(year=year, month=month, day=day)


def _resolve_period_end(
    paid_at: datetime | None, billing_interval: str, provider_period_end: datetime | None
) -> datetime | None:
    """End of the period this payment bought.

    Paystack reports ``next_payment_date`` for *subscription*-backed charges.
    Our checkout creates a one-off transaction - deliberately, because RELIASTRA
    owns the billing state and does not put customers on a recurring provider
    plan it cannot reprice - so that field is normally empty, and the period
    would be left null. A null period end reads as "never expires" to every
    entitlement check, which is how a paid month becomes free forever.

    So the end is derived from the interval the customer actually paid for: one
    calendar month or twelve, counted from when payment was taken. A provider
    date, when there is one, wins - it is the more authoritative figure of the
    two.
    """
    if provider_period_end is not None:
        return provider_period_end
    if paid_at is None:
        return None
    return _add_calendar_months(paid_at, 12 if billing_interval == ANNUAL_INTERVAL else 1)


def _parse_datetime(value: Any) -> datetime | None:
    if not value:
        return None
    if isinstance(value, datetime):
        return value
    if isinstance(value, str):
        try:
            return datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            return None
    return None


def transaction_metadata(raw: Any) -> dict[str, Any]:
    """Read Paystack's ``metadata`` as a mapping, whatever shape it arrives in.

    The Initialize Transaction reference types ``metadata`` as a *stringified*
    JSON object, while verify and the webhook events return the object back in
    whichever form they received it - and in practice RELIASTRA has seen both
    encodings across API versions. A strict ``isinstance(x, dict)`` therefore
    reads a legitimately-returned JSON string as "no metadata", which would
    silently refuse a paid customer's organization association and never
    activate their subscription.

    Malformed or absent metadata resolves to ``{}`` so the caller's own
    integrity check rejects it with a clear reason, rather than this helper
    raising inside a payment verification.
    """
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        text = raw.strip()
        if not text:
            return {}
        try:
            parsed = json.loads(text)
        except ValueError:
            logger.warning("Ignoring Paystack metadata that is not valid JSON")
            return {}
        return parsed if isinstance(parsed, dict) else {}
    return {}


def _optional_uuid(value: Any) -> uuid.UUID | None:
    """Parse a UUID from untrusted input without ever raising.

    Anything read back out of a Paystack payload is attacker-influenceable in
    principle - ``metadata`` is echoed by the provider exactly as it was sent,
    and a payment page reference can be replayed against the verify endpoint
    - so an unparseable value must degrade to "unknown", not blow up. It would
    be worse than cosmetic here: the persistence call this feeds sits inside a
    ``try/except`` that deliberately swallows failures so a bookkeeping problem
    cannot turn a successful payment into a failed verification, and a raised
    ``ValueError`` would quietly drop the charge record with it.
    """
    if value in (None, ""):
        return None
    try:
        return uuid.UUID(str(value))
    except (ValueError, TypeError, AttributeError):
        return None


def _authorization_fields(data: dict[str, Any]) -> dict[str, Any]:
    """Masked card fields from Paystack's authorization object. Never the full card number."""
    auth = data.get("authorization")
    if not isinstance(auth, dict):
        return {}
    out: dict[str, Any] = {}
    brand = str(auth.get("brand") or auth.get("card_type") or "").strip()[:50]
    last4 = str(auth.get("last4") or "").strip()[:4]
    channel = str(auth.get("channel") or data.get("channel") or "").strip()[:40]
    if brand:
        out["payment_method_brand"] = brand
    if last4:
        out["payment_method_last4"] = last4
    try:
        month = int(auth["exp_month"]) if auth.get("exp_month") not in (None, "") else None
    except (TypeError, ValueError):
        month = None
    try:
        year = int(auth["exp_year"]) if auth.get("exp_year") not in (None, "") else None
    except (TypeError, ValueError):
        year = None
    if month:
        out["payment_method_exp_month"] = month
    if year:
        out["payment_method_exp_year"] = year
    if channel:
        out["payment_method_channel"] = channel
    return out


def _provider_metadata(data: dict[str, Any]) -> dict[str, Any]:
    meta = {
        key: data.get(key)
        for key in (
            "id",
            "domain",
            "channel",
            "gateway_reference",
            "status",
            "transaction_date",
        )
        if data.get(key) is not None
    }
    auth = _authorization_fields(data)
    if auth.get("payment_method_brand"):
        meta["card_brand"] = auth["payment_method_brand"]
        meta["brand"] = auth["payment_method_brand"]
    if auth.get("payment_method_last4"):
        meta["last4"] = auth["payment_method_last4"]
    return meta


def _normalized_plan(data: dict[str, Any]) -> str:
    metadata = transaction_metadata(data.get("metadata"))
    candidate: Any = metadata.get("plan")
    if not candidate:
        plan_data = data.get("plan")
        if isinstance(plan_data, dict):
            candidate = plan_data.get("name") or plan_data.get("plan_code")
        elif isinstance(plan_data, str):
            candidate = plan_data
    # Fall back to PRO for legacy free-form payloads; normalize_plan maps
    # legacy names to canonical ones.
    return normalize_plan(str(candidate or Plan.PRO.value))


def _billing_interval(data: dict[str, Any]) -> str:
    """Resolve the billing interval from metadata (default monthly)."""
    metadata = transaction_metadata(data.get("metadata"))
    candidate = str(metadata.get("billing_interval") or BillingInterval.MONTHLY.value).strip().lower()
    if candidate in {BillingInterval.MONTHLY.value, BillingInterval.ANNUAL.value}:
        return candidate
    return BillingInterval.MONTHLY.value
