import hashlib
import hmac
import json
import logging
import uuid
from calendar import monthrange
from datetime import datetime, timezone
from typing import Any, Sequence

import httpx
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.core.checkout_reasons import (
    CheckoutReason,
    CheckoutRejectedException,
)
from app.core.exceptions import (
    ResourceNotFoundException,
    UnauthorizedException,
    ValidationException,
    ServiceUnavailableException,
)
from app.core.permissions import (
    PLAN_AMOUNTS,
    PLAN_ANNUAL_AMOUNTS,
    PLAN_DISPLAY_NAMES,
    PLAN_FEATURES,
    TRIAL_DAYS,
    Plan,
    get_dependency_limit,
    get_effective_entitlements,
    get_min_check_interval,
    get_plan_billing_availability,
    get_plan_price_usd,
    get_retention_days,
    get_team_limit,
    is_paid_plan,
    normalize_plan,
)
from app.core.payment_channels import (
    checkout_channels,
    method_is_enabled,
    payment_method_descriptors,
    resolve_checkout_channels,
    settled_channel_is_acceptable,
)
from app.core.payment_disclosure import currency_payload
from app.core.payment_pricing import (
    ANNUAL as ANNUAL_INTERVAL,
    MONTHLY as MONTHLY_INTERVAL,
    PAYMENT_PROVIDER,
    PaymentPrice,
    format_money,
    payment_currency,
    resolve_payment_price,
)
from app.modules.billing.notifications import (
    PaymentSummary,
    send_payment_receipt_email,
    send_subscription_confirmed_email,
)
from app.modules.billing.repository import BillingRepository
from app.modules.billing.schemas import (
    BillingInterval,
    BillingTransactionResponse,
    BillingTransactionsResponse,
    CheckoutQuoteResponse,
    PaymentCurrencyResponse,
    InitializePaymentRequest,
    InitializePaymentResponse,
    PaystackWebhookResponse,
    PlanDetailsResponse,
    VerifyTransactionResponse,
)

logger = logging.getLogger(__name__)

# P3 fix: pooled HTTP client for Paystack (like checks service) — one pool
# instead of a fresh TCP/TLS handshake per initialize/verify. Timeouts stay
# per-request via the client's default timeout.
_paystack_http_client: httpx.AsyncClient | None = None


def _get_paystack_http_client() -> httpx.AsyncClient:
    global _paystack_http_client
    if _paystack_http_client is None:
        _paystack_http_client = httpx.AsyncClient(
            limits=httpx.Limits(max_connections=20, max_keepalive_connections=5),
            timeout=httpx.Timeout(10.0),
        )
    return _paystack_http_client


async def close_paystack_http_client() -> None:
    global _paystack_http_client
    if _paystack_http_client is not None:
        await _paystack_http_client.aclose()
        _paystack_http_client = None


class PaystackClient:
    """Small async Paystack client built on the project's existing HTTP stack."""

    def __init__(self) -> None:
        self.base_url = settings.PAYSTACK_BASE_URL.rstrip("/")
        self.secret_key = settings.PAYSTACK_SECRET_KEY

    def _headers(self) -> dict[str, str]:
        if not self.secret_key:
            raise ValidationException("Paystack is not configured")
        return {
            "Authorization": f"Bearer {self.secret_key}",
            "Content-Type": "application/json",
        }

    async def initialize_transaction(
        self,
        email: str,
        amount: int,
        plan: str,
        metadata: dict[str, str] | None = None,
        currency: str | None = None,
        callback_url: str | None = None,
        channels: list[str] | None = None,
        reference: str | None = None,
    ) -> dict[str, Any]:
        """Create a Paystack transaction for exactly ``amount`` minor units.

        Two parameters here are load-bearing and were not obvious:

        * ``channels`` is always sent. Without it Paystack shows whatever the
          dashboard has ticked, which on a Nigerian merchant account means
          USSD, Pay with Bank and QR appear in front of a customer in
          Germany. RELIASTRA declares its own set
          (:mod:`app.core.payment_channels`) so the checkout stays card-only
          regardless of what the dashboard is later changed to.
        * the ``plan`` field is *not* sent. Paystack's Initialize Transaction
          reference defines it as the code of a predefined Paystack plan
          (``PLN_...``) and states that supplying it "would invalidate the
          value provided in ``amount``". RELIASTRA's plans are priced by
          :mod:`app.core.payment_pricing`, not by Paystack plan objects, so the
          plan name travels in ``metadata`` for reconciliation instead —
          sending ``"pro"`` there would either fail initialization or let the
          dashboard plan silently reprice the transaction.

        ``reference`` is generated by RELIASTRA rather than left to Paystack so
        the string itself carries the organization and can be correlated in
        logs, and so an initialization can be re-attempted for the same
        pending checkout without creating a second orphan transaction.
        """
        client = _get_paystack_http_client()
        payload: dict[str, Any] = {
            "email": email,
            "amount": amount,
            # Currency MUST be explicit: without it Paystack charges in
            # the merchant account's default currency, silently
            # repricing the plan. The caller passes the currency that
            # this amount was resolved in (payment_pricing), never a
            # separately-read setting, so the amount and its currency
            # can never drift apart.
            "currency": (currency or payment_currency()),
            "channels": channels or checkout_channels(),
            "metadata": metadata or {},
        }
        if reference:
            payload["reference"] = reference
        if callback_url:
            # Bring the customer back to RELIASTRA's checkout so the exact
            # charge is confirmed there (see the ?reference= handler in the
            # checkout page) instead of on a blank provider page.
            payload["callback_url"] = callback_url
        response = await client.post(
            f"{self.base_url}/transaction/initialize",
            headers=self._headers(),
            json=payload,
        )
        response.raise_for_status()
        return response.json()

    async def verify_transaction(self, reference: str) -> dict[str, Any]:
        client = _get_paystack_http_client()
        response = await client.get(
            f"{self.base_url}/transaction/verify/{reference}",
            headers=self._headers(),
        )
        response.raise_for_status()
        return response.json()

    async def fetch_plan(self, plan_code_or_id: str) -> dict[str, Any] | None:
        client = _get_paystack_http_client()
        response = await client.get(
            f"{self.base_url}/plan/{plan_code_or_id}",
            headers=self._headers(),
        )
        if response.status_code == 404:
            return None
        response.raise_for_status()
        return response.json()


paystack_client = PaystackClient()

# PRODUCT PRICING (USD list price: PLAN_PRICES_USD / PLAN_AMOUNTS in
# ``app.core.permissions``) and PAYMENT PRICING (the amount actually charged
# through Paystack, in the processing currency) are two separate concepts and
# are resolved through ``app.core.payment_pricing``. Nothing converts one into
# the other: for a non-USD processor the business publishes explicit payment
# prices (PAYSTACK_NGN_PLAN_PRICES), and self-serve checkout is disabled for
# any plan whose payment price is missing rather than silently charging the
# USD minor-unit figure in another currency.
#
# ENTERPRISE and FREE are NOT self-serve: enterprise routes to Contact Sales,
# and free has nothing to charge.
_MONTHLY_AMOUNTS = PLAN_AMOUNTS
_ANNUAL_AMOUNTS = PLAN_ANNUAL_AMOUNTS


def _price_for(plan: str, interval: str) -> PaymentPrice:
    """Canonical product+payment price for a plan/interval pair."""
    return resolve_payment_price(
        plan, ANNUAL_INTERVAL if interval == BillingInterval.ANNUAL.value else MONTHLY_INTERVAL
    )


def _price_token(price: PaymentPrice, channels: Sequence[str]) -> str:
    """Short digest of the exact figures a checkout quote was issued from.

    Not a signature and not a capability: it cannot price anything, choose a
    currency, or be edited into a different charge. It exists only so the
    checkout page can prove which quote the customer looked at, and so we can
    stop a payment rather than send Paystack a number nobody approved.
    """
    material = "|".join(
        [
            str(price.plan),
            str(price.interval),
            str(price.product_currency),
            str(price.product_amount),
            str(price.payment_currency),
            str(price.payment_amount),
            ",".join(sorted(channels)),
        ]
    )
    return hashlib.sha256(material.encode("utf-8")).hexdigest()[:16]


def _amount_for_interval(plan: str, interval: str) -> int | None:
    """The amount (minor units of the processing currency) a checkout pays.

    Kept as a helper because the webhook/verify integrity check needs the same
    single source of truth the initializer uses — if these two ever disagreed,
    every correctly priced payment would be rejected as "undersized".
    """
    return _price_for(plan, interval).payment_amount


def _add_calendar_months(moment: datetime, months: int) -> datetime:
    """Same day-of-month ``months`` later, clamped to shorter months."""
    year = moment.year + (moment.month - 1 + months) // 12
    month = (moment.month - 1 + months) % 12 + 1
    day = min(moment.day, monthrange(year, month)[1])
    return moment.replace(year=year, month=month, day=day)


def _resolve_period_end(
    paid_at: datetime | None, billing_interval: str, provider_period_end: datetime | None
) -> datetime | None:
    """End of the period this payment bought.

    Paystack reports ``next_payment_date`` for *subscription*-backed charges.
    Our checkout creates a one-off transaction — deliberately, because RELIASTRA
    owns the billing state and does not put customers on a recurring provider
    plan it cannot reprice — so that field is normally empty, and the period
    would be left null. A null period end reads as "never expires" to every
    entitlement check, which is how a paid month becomes free forever.

    So the end is derived from the interval the customer actually paid for: one
    calendar month or twelve, counted from when payment was taken. A provider
    date, when there is one, wins — it is the more authoritative figure of the
    two.
    """
    if provider_period_end is not None:
        return provider_period_end
    if paid_at is None:
        return None
    return _add_calendar_months(paid_at, 12 if billing_interval == ANNUAL_INTERVAL else 1)


def _parse_datetime(value: Any) -> datetime | None:
    if not value:
        return None
    if isinstance(value, datetime):
        return value
    if isinstance(value, str):
        try:
            return datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            return None
    return None


def transaction_metadata(raw: Any) -> dict[str, Any]:
    """Read Paystack's ``metadata`` as a mapping, whatever shape it arrives in.

    The Initialize Transaction reference types ``metadata`` as a *stringified*
    JSON object, while verify and the webhook events return the object back in
    whichever form they received it — and in practice RELIASTRA has seen both
    encodings across API versions. A strict ``isinstance(x, dict)`` therefore
    reads a legitimately-returned JSON string as "no metadata", which would
    silently refuse a paid customer's organization association and never
    activate their subscription.

    Malformed or absent metadata resolves to ``{}`` so the caller's own
    integrity check rejects it with a clear reason, rather than this helper
    raising inside a payment verification.
    """
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        text = raw.strip()
        if not text:
            return {}
        try:
            parsed = json.loads(text)
        except ValueError:
            logger.warning("Ignoring Paystack metadata that is not valid JSON")
            return {}
        return parsed if isinstance(parsed, dict) else {}
    return {}


def _optional_uuid(value: Any) -> uuid.UUID | None:
    """Parse a UUID from untrusted input without ever raising.

    Anything read back out of a Paystack payload is attacker-influenceable in
    principle — ``metadata`` is echoed by the provider exactly as it was sent,
    and a payment page reference can be replayed against the verify endpoint
    — so an unparseable value must degrade to "unknown", not blow up. It would
    be worse than cosmetic here: the persistence call this feeds sits inside a
    ``try/except`` that deliberately swallows failures so a bookkeeping problem
    cannot turn a successful payment into a failed verification, and a raised
    ``ValueError`` would quietly drop the charge record with it.
    """
    if value in (None, ""):
        return None
    try:
        return uuid.UUID(str(value))
    except (ValueError, TypeError, AttributeError):
        return None


def _reason_details(reason: str, **extra: Any) -> list[dict[str, Any]]:
    """``details`` payload carrying a machine-readable reason slug."""
    payload: list[dict[str, Any]] = [{"field": "reason", "issue": reason}]
    for key, value in extra.items():
        if value is not None:
            payload.append({"field": key, "issue": str(value)})
    return payload


def _normalized_plan(data: dict[str, Any]) -> str:
    metadata = transaction_metadata(data.get("metadata"))
    candidate: Any = metadata.get("plan")
    if not candidate:
        plan_data = data.get("plan")
        if isinstance(plan_data, dict):
            candidate = plan_data.get("name") or plan_data.get("plan_code")
        elif isinstance(plan_data, str):
            candidate = plan_data
    # Fall back to PRO for legacy free-form payloads; normalize_plan maps
    # legacy names to canonical ones.
    return normalize_plan(str(candidate or Plan.PRO.value))


def _billing_interval(data: dict[str, Any]) -> str:
    """Resolve the billing interval from metadata (default monthly)."""
    metadata = transaction_metadata(data.get("metadata"))
    candidate = str(metadata.get("billing_interval") or BillingInterval.MONTHLY.value).strip().lower()
    if candidate in {BillingInterval.MONTHLY.value, BillingInterval.ANNUAL.value}:
        return candidate
    return BillingInterval.MONTHLY.value


class BillingService:
    def __init__(
        self,
        repository: BillingRepository = BillingRepository(),
        client: PaystackClient = paystack_client,
    ) -> None:
        self.repository = repository
        self.client = client

    async def get_plan_details(
        self, session: AsyncSession, org_id: uuid.UUID
    ) -> PlanDetailsResponse:
        org = await self.repository.get_org(session, org_id)
        if not org:
            raise ResourceNotFoundException("Organization not found")
        subscription = await self.repository.get_subscription(session, org_id)

        # Centralized evaluation-aware entitlement resolution. Server time only.
        ent = get_effective_entitlements(org)
        effective_plan = ent["effective_plan"]
        base_price = get_plan_price_usd(effective_plan)
        # Real account consequences for the fallback message (never fabricated).
        fallback_info = await self._build_fallback_info(session, org, ent)
        effective_is_custom = get_plan_billing_availability(effective_plan) == "contact_sales"
        return PlanDetailsResponse(
            org_id=org.id,
            plan=ent["subscription_plan"],
            effective_plan=effective_plan,
            is_trial_active=ent["is_evaluation_active"],
            trial_days_remaining=ent["evaluation_days_remaining"],
            trial_length_days=TRIAL_DAYS,
            is_evaluation_active=ent["is_evaluation_active"],
            evaluation_status=ent["evaluation_status"],
            evaluation_started_at=ent["evaluation_started_at"],
            evaluation_expires_at=ent["evaluation_expires_at"],
            evaluation_days_remaining=ent["evaluation_days_remaining"],
            evaluation_used=ent["evaluation_used"],
            max_dependencies=get_dependency_limit(effective_plan),
            max_team_members=get_team_limit(effective_plan),
            min_check_interval_seconds=get_min_check_interval(effective_plan),
            data_retention_days=get_retention_days(effective_plan),
            effective_features=ent["effective_features"],
            fallback_info=fallback_info,
            subscription_status=subscription.status if subscription else None,
            current_period_end=(
                subscription.current_period_end if subscription else None
            ),
            price_usd=base_price,
            billing_interval=(
                subscription.billing_interval if subscription is not None else None
            ),
            # Enterprise uses custom pricing — never advertise a numeric price.
            effective_is_custom=effective_is_custom,
            # Payment currency + canonical disclosure (+ the display-only FX
            # reference), resolved from the same source the checkout uses —
            # never a frontend literal.
            payment=PaymentCurrencyResponse(**(await currency_payload())),
            **self._next_charge_fields(subscription),
        )

    @staticmethod
    def _next_charge_fields(subscription) -> dict:
        """Next renewal amount for the billing page, from the payment catalog.

        Empty when there is no active paid subscription: the UI must not show
        a "next charge" figure the customer will never be billed.
        """
        if subscription is None or subscription.plan == Plan.FREE.value:
            return {}
        price = resolve_payment_price(
            subscription.plan, subscription.billing_interval or MONTHLY_INTERVAL
        )
        if not price.is_configured:
            return {}
        return {
            "next_charge_amount_minor": price.payment_amount,
            "next_charge_amount_display": format_money(
                price.payment_amount, price.payment_currency
            ),
        }

    async def get_transactions(
        self, session: AsyncSession, org_id: uuid.UUID
    ) -> BillingTransactionsResponse:
        """Payment history with the ACTUAL charged amount/currency per payment.

        Every figure comes from the persisted provider response — never from
        re-resolving today's price list — so history stays truthful even after
        a repricing. Display strings are formatted here for the same reason
        every other amount string is: the UI never composes money itself.
        """
        from app.core.permissions import get_plan_display_name

        items = []
        for tx in await self.repository.list_transactions(session, org_id):
            items.append(
                BillingTransactionResponse(
                    id=tx.id,
                    reference=tx.reference,
                    provider=tx.provider.capitalize() if tx.provider else "Paystack",
                    plan=tx.plan,
                    display_plan=get_plan_display_name(tx.plan),
                    billing_interval=tx.billing_interval,
                    status=tx.status,
                    product_currency=tx.product_currency,
                    product_amount_minor=tx.product_amount_minor,
                    product_price_display=format_money(
                        tx.product_amount_minor, tx.product_currency
                    )
                    or None,
                    charged_currency=tx.charged_currency,
                    charged_amount_minor=tx.charged_amount_minor,
                    charged_amount_display=format_money(
                        tx.charged_amount_minor, tx.charged_currency
                    ),
                    paid_at=tx.paid_at,
                    verified_at=tx.verified_at,
                    period_start=tx.period_start,
                    period_end=tx.period_end,
                    created_at=tx.created_at,
                    # A duplicate is shown, never hidden: a customer who paid
                    # twice for one month needs to see both lines and the
                    # credit, not a history that quietly dropped one.
                    duplicate=bool(tx.duplicate),
                )
            )
        return BillingTransactionsResponse(
            items=items,
            payment=PaymentCurrencyResponse(**await currency_payload()),
        )

    async def _build_fallback_info(
        self, session: AsyncSession, org, ent: dict
    ) -> dict | None:
        """Build the account-specific post-evaluation consequences.

        e.g.  17 dependencies configured, 1 active on Free, 16 paused.
        Uses real counts, never invented numbers, so the fallback message is
        commercially meaningful and explainable.
        """
        try:
            from app.modules.dependencies.repository import DependencyRepository
            from app.modules.organizations.repository import OrganizationRepository

            total_deps = await DependencyRepository.count_for_org(session, org.id)
            effective = ent["effective_plan"]
            free_limit = get_dependency_limit(Plan.FREE.value) or 0
            current_limit = get_dependency_limit(effective)
            # Enterprise/custom plans have no fixed numeric limit.
            if current_limit is None:
                current_limit = max(total_deps, free_limit)
            # Estimate paused if they were to fall back now
            would_pause = max(0, total_deps - free_limit) if ent["is_evaluation_active"] else 0
            members = await OrganizationRepository.list_members(session, org.id)
            team_count = len(members)
            team_free = get_team_limit(Plan.FREE.value) or 1
            team_current = get_team_limit(effective)
            if team_current is None:
                team_current = max(team_count, team_free)
            return {
                "dependencies_configured": total_deps,
                "dependencies_active": min(total_deps, current_limit),
                "dependencies_paused_if_expired": would_pause,
                "free_dependency_limit": free_limit,
                "current_dependency_limit": current_limit,
                "team_members": team_count,
                "team_free_limit": team_free,
                "team_current_limit": team_current,
                "evidence_available": bool(ent["effective_features"].get("evidence_generation")),
                "evidence_free_available": bool(PLAN_FEATURES[Plan.FREE.value].get("evidence_generation")),
                "api_available": bool(ent["effective_features"].get("api_access")),
                "retention_days_current": get_retention_days(effective),
                "retention_days_free": get_retention_days(Plan.FREE.value),
            }
        except Exception:
            return None

    async def checkout_quote(
        self,
        session: AsyncSession,
        org_id: uuid.UUID,
        *,
        plan: str,
        billing_interval: str = MONTHLY_INTERVAL,
    ) -> CheckoutQuoteResponse:
        """The authoritative render-model for RELIASTRA's checkout page.

        Why an endpoint instead of letting the checkout page compute from the
        pricing list it already fetched: the page would then be *composing* a
        price — plan id plus interval in, "₦60,000" out — and any bug in that
        composition is a customer who was shown one number and charged another.
        So the page asks, and displays. It receives the product price, the
        payment amount, the currency names, the disclosure, the FX reference and
        the available payment methods as finished strings from the same
        resolvers that will price the actual transaction, which is the only way
        the review screen and Paystack can be guaranteed to agree.

        The response also gates the flow. ``available=False`` with a reason is
        the state where checkout must not be offered at all — an unpublished
        payment price for the processing currency, or a plan that is not
        self-serve — and the page then explains instead of presenting a CTA
        that would fail mid-payment.
        """
        from app.core.permissions import (
            PLAN_DESCRIPTIONS,
            PLAN_FEATURES,
            get_plan_billing_availability,
        )

        normalized = normalize_plan(plan)
        interval = (billing_interval or MONTHLY_INTERVAL).strip().lower()
        interval = ANNUAL_INTERVAL if interval == ANNUAL_INTERVAL else MONTHLY_INTERVAL
        price = resolve_payment_price(normalized, interval)
        methods = payment_method_descriptors()
        policy = resolve_checkout_channels()
        disclosure = await currency_payload()

        org = await self.repository.get_org(session, org_id)
        subscription = await self.repository.get_subscription(session, org_id)

        # Whose mailbox the receipt goes to — shown for confirmation, and sent
        # to Paystack as the payer identity. Read from the organization's owner,
        # never trusted from a request body that could name someone else.
        billing_email = None
        from app.modules.organizations.repository import OrganizationRepository
        from app.modules.users.repository import UserRepository

        try:
            members = await OrganizationRepository.list_members(session, org_id)
            owner = next((m for m in members if m.role == "owner"), None)
            if owner is not None:
                user = await UserRepository.get_by_id(session, owner.user_id)
                billing_email = user.email if user else None
        except Exception:  # pragma: no cover - identity is advisory, not gating
            logger.warning("Could not resolve billing email for org %s", org_id)

        current_plan = subscription.plan if subscription is not None else None
        current_interval = (
            subscription.billing_interval if subscription is not None else None
        )
        already_subscribed = bool(
            subscription is not None
            and subscription.status == "active"
            and current_plan == normalized
            and (current_interval or MONTHLY_INTERVAL) == interval
        )

        available = True
        reason: str | None = None
        message: str | None = None
        if get_plan_billing_availability(normalized) == "contact_sales":
            available, reason = False, CheckoutReason.PLAN_NOT_SELFSERVE
            message = (
                "Enterprise is set up with our team rather than through "
                "self-serve checkout."
            )
        elif not price.is_configured:
            available, reason = False, CheckoutReason.PRICE_NOT_CONFIGURED
            message = (
                f"Our {price.payment_currency} price for this plan is being "
                "finalized. Contact billing@reliastra.com and we will set up "
                "your subscription directly."
            )
        elif not settings.PAYSTACK_SECRET_KEY:
            # Configuration gap, never a customer-facing detail: the checkout
            # says "unavailable, try again / contact us" and no amount is
            # invented to keep the button alive.
            available, reason = False, CheckoutReason.PROVIDER_UNAVAILABLE
            message = (
                "Online payment is temporarily unavailable. No charge has been "
                "made — please try again shortly or contact "
                "billing@reliastra.com."
            )

        trial_note = None
        plan_details = await self.get_plan_details(session, org_id)
        if plan_details.is_trial_active:
            trial_note = (
                f"Your {plan_details.trial_days_remaining}-day evaluation is "
                "still running. Subscribing now starts billing immediately and "
                "ends the evaluation."
            )

        return CheckoutQuoteResponse(
            plan=normalized,
            display_plan=PLAN_DISPLAY_NAMES.get(normalized, normalized.title()),
            description=PLAN_DESCRIPTIONS.get(normalized, ""),
            features=PLAN_FEATURES.get(normalized),
            billing_interval=interval,
            product_currency=price.product_currency,
            product_amount_minor=price.product_amount,
            product_price_display=format_money(
                price.product_amount, price.product_currency
            )
            or None,
            payment_currency=price.payment_currency,
            payment_amount_minor=price.payment_amount,
            payment_amount_display=format_money(
                price.payment_amount, price.payment_currency
            )
            or None,
            payment_currency_name=price.payment_currency_name,
            payment_provider=PAYMENT_PROVIDER,
            # Straight index, not a fallback: ``currency_payload()`` is the one
            # disclosure object every payment surface renders from, so the
            # checkout cannot drift to a different provider label than pricing
            # and billing already show.
            payment_provider_display=disclosure["payment_provider_display"],
            period_word="year" if interval == ANNUAL_INTERVAL else "month",
            currency_notice=disclosure.get("notice"),
            fx_reference=disclosure.get("fx_reference"),
            payment_methods=methods,
            channels=list(policy.enabled),
            price_token=_price_token(price, policy.enabled),
            organization_name=getattr(org, "name", None),
            billing_email=billing_email,
            current_plan=current_plan,
            current_interval=current_interval,
            already_subscribed=already_subscribed,
            available=available,
            unavailable_reason=reason,
            unavailable_message=message,
            checkout_enabled=bool(settings.PAYSTACK_SECRET_KEY),
            trial_note=trial_note,
        )

    async def initialize_payment(
        self,
        session: AsyncSession,
        org_id: uuid.UUID,
        request: InitializePaymentRequest,
        *,
        user_id: uuid.UUID | None = None,
    ) -> InitializePaymentResponse:
        """Create the Paystack transaction for one organization's checkout.

        Every number that reaches Paystack is resolved here, from server-side
        configuration — ``request`` carries a plan and a billing interval and
        nothing else. There is deliberately no amount, currency or channel
        field to accept: a client cannot price its own subscription, choose
        which rails it pays through, or pick the currency its charge settles
        in. The price the customer was shown and the money RELIASTRA agrees to
        receive are the same fact, and only the backend may hold it.
        """
        org = await self.repository.get_org(session, org_id)
        if not org:
            raise ResourceNotFoundException("Organization not found")

        plan = normalize_plan(request.plan)

        # Enterprise is NOT self-serve — it routes to Contact Sales. Never
        # create a fake $0 checkout or invent a numeric enterprise price.
        if get_plan_billing_availability(plan) == "contact_sales":
            raise CheckoutRejectedException(
                CheckoutReason.PLAN_NOT_SELFSERVE,
                "This plan is set up with our team rather than through "
                "self-serve checkout. Contact sales and we will have it "
                "running for you.",
            )
        # Free is not a paid plan; there is nothing to charge.
        if not is_paid_plan(plan):
            raise ValidationException(
                f"Invalid paid plan: '{plan}'. The only self-serve paid plan is PRO."
            )
        if plan not in PLAN_AMOUNTS:
            raise ValidationException(
                f"Plan '{plan}' is not available for self-serve checkout. "
                f"Please contact sales."
            )

        interval = request.billing_interval.value
        price = _price_for(plan, interval)
        if not price.is_configured:
            # The product price exists, but the business has not published a
            # PAYMENT price for the processing currency. Charging the USD
            # minor-unit figure as Naira would mis-bill the customer, so we
            # stop here — before any Paystack transaction exists.
            logger.warning(
                "Checkout disabled for plan '%s' (%s): no %s payment price published",
                plan,
                interval,
                price.payment_currency,
            )
            raise CheckoutRejectedException(
                CheckoutReason.PRICE_NOT_CONFIGURED,
                f"Our {price.payment_currency} price for this plan is being "
                "finalized. Contact billing@reliastra.com and we will set up "
                "your subscription directly.",
                status_code=409,
            )
        base_amount = int(price.payment_amount or 0)

        # The customer may choose *which* offered method to pay with; they may
        # not choose one RELIASTRA has not enabled. Rejecting here means a
        # hand-edited request never reaches Paystack asking for a channel the
        # checkout explicitly refuses to support for global buyers.
        method_id = (request.payment_method or "").strip()
        if method_id and not method_is_enabled(method_id):
            raise CheckoutRejectedException(
                CheckoutReason.METHOD_UNAVAILABLE,
                "That payment method is not available for this checkout. "
                "Please continue with an international card.",
                status_code=409,
                extra={"requested": method_id},
            )
        policy = resolve_checkout_channels()

        # The quote and this transaction are priced by the same resolution — but
        # a checkout page can sit open across an operator repricing the plan, and
        # the customer would then approve one number while we sent another. The
        # page echoes the token its quote was issued under (never an amount: a
        # token cannot price anything), and a mismatch stops the payment instead
        # of proceeding against a figure nobody approved.
        if request.expected_price_token:
            current_token = _price_token(price, policy.enabled)
            if not hmac.compare_digest(
                str(request.expected_price_token), current_token
            ):
                logger.warning(
                    "Checkout quote for org %s is stale (plan %s / %s); refusing to "
                    "charge the re-resolved price",
                    org_id,
                    plan,
                    interval,
                )
                raise CheckoutRejectedException(
                    CheckoutReason.QUOTE_STALE,
                    "The price shown on this page is no longer the price our system "
                    "has, so nothing has been charged. Reload to see the current "
                    "price and continue from there.",
                    status_code=409,
                )

        # The payer address handed to Paystack is also the mailbox its receipt
        # lands in, so it is chosen from this organization rather than from the
        # request. A client may name a member of this workspace (a teammate
        # paying on its behalf); naming an address outside it is ignored, not
        # obeyed — otherwise any authenticated user could send somebody else's
        # payment confirmation to a stranger.
        from app.modules.organizations.repository import OrganizationRepository
        from app.modules.users.repository import UserRepository

        members = await OrganizationRepository.list_members(session, org_id)
        owner = next((member for member in members if member.role == "owner"), None)
        owner_user = (
            await UserRepository.get_by_id(session, owner.user_id) if owner else None
        )
        email = owner_user.email if owner_user else None
        requested_email = str(request.email).strip() if request.email else ""
        if requested_email:
            claimed = await UserRepository.get_by_email(session, requested_email)
            if claimed is not None and any(
                member.user_id == claimed.id for member in members
            ):
                email = claimed.email
            else:
                logger.warning(
                    "Ignoring a payer email on checkout for org %s that belongs to "
                    "no member of that organization",
                    org_id,
                )
        if not email:
            raise ValidationException(
                "No email is available for payment initialization"
            )

        from app.infrastructure.email_layout import frontend_url

        # RELIASTRA generates the reference. Paystack's docs recommend exactly
        # this so the merchant owns one identifier from first click through to
        # reconciliation, and embedding the organization prefix makes a
        # misfiled payment findable in logs without opening the payload. Only
        # alphanumerics and ``-``, ``.``, ``=`` are permitted by the API.
        reference = f"reliastra-{org_id.hex[:8]}-{uuid.uuid4().hex[:16]}"

        try:
            result = await self.client.initialize_transaction(
                email=email,
                amount=base_amount,
                plan=plan,
                # The currency sent here is the currency every RELIASTRA
                # surface displays to the customer, resolved from the same
                # payment-pricing source of truth.
                currency=price.payment_currency,
                # Channels are declared per transaction, never inherited from
                # the dashboard: a global customer is offered only the rails
                # that can actually settle from their country.
                channels=list(policy.enabled),
                reference=reference,
                # Return the payer to RELIASTRA's checkout so the exact charge
                # is restated and verified there (the ?reference= handler).
                callback_url=frontend_url("/checkout"),
                metadata={
                    "org_id": str(org_id),
                    "plan": plan,
                    "billing_interval": interval,
                    "currency": price.payment_currency,
                    "amount_minor": str(base_amount),
                    "product_currency": price.product_currency,
                    "product_amount_minor": str(price.product_amount or 0),
                    "payment_provider": PAYMENT_PROVIDER,
                    "channels": ",".join(policy.enabled),
                    # Who authorized this purchase, for the billing record.
                    # Never card holder data: RELIASTRA holds none.
                    "actor_user_id": str(user_id) if user_id else None,
                },
            )
        except httpx.HTTPError as exc:
            # Logged with detail, answered without it. A provider outage has a
            # specific customer-facing shape — nothing moved, try again — that
            # no amount of upstream text improves.
            logger.warning("Paystack initialization failed: %s", exc)
            raise CheckoutRejectedException(
                CheckoutReason.PROVIDER_UNAVAILABLE,
                "We could not reach our payment provider just now. No money "
                "has moved — please try again in a moment.",
                status_code=503,
            ) from exc

        data = result.get("data") if isinstance(result.get("data"), dict) else {}
        if not result.get("status") or not data:
            logger.warning(
                "Paystack rejected initialization for org %s: %s",
                org_id,
                str(result.get("message") or "")[:200],
            )
            raise CheckoutRejectedException(
                CheckoutReason.PROVIDER_UNAVAILABLE,
                "We could not start the payment. No money has moved — please "
                "try again, or contact billing@reliastra.com if this persists.",
                status_code=503,
            )

        # Funnel analytics: this organization reached checkout with a
        # reachable email. If they never pay, sales can follow up manually.
        from app.modules.analytics.service import analytics_service

        await analytics_service.record_checkout_started(
            str(org_id),
            email=email,
            plan=plan,
            amount_minor=base_amount,
            reference=str(data.get("reference") or ""),
        )
        try:
            return InitializePaymentResponse(
                authorization_url=data["authorization_url"],
                reference=str(data.get("reference") or reference),
                access_code=data["access_code"],
                # The public key is a *publishable* credential — Paystack's
                # InlineJS reference takes it in browser code. The secret key
                # never leaves this process.
                public_key=settings.PAYSTACK_PUBLIC_KEY or None,
                inline_js_enabled=bool(settings.PAYSTACK_INLINE_JS_ENABLED)
                and bool(settings.PAYSTACK_PUBLIC_KEY),
                inline_js_url=settings.PAYSTACK_INLINE_JS_URL,
                # Exactly the rails this transaction was opened with, so the
                # payment experience that launches cannot disagree with the
                # method the customer approved on the review screen.
                channels=list(policy.enabled),
                payment_methods=payment_method_descriptors(),
                # Echo of the real charge, so the confirmation screen and any
                # post-redirect page state the same currency Paystack holds.
                amount_minor=base_amount,
                currency=price.payment_currency,
                amount_display=format_money(base_amount, price.payment_currency),
                plan=plan,
                billing_interval=interval,
                # …and the product price it corresponds to, so the mandatory
                # "Product price / Actual charge / Payment provider" block is
                # backend-sourced end to end.
                product_currency=price.product_currency,
                product_amount_minor=price.product_amount,
                product_price_display=format_money(
                    price.product_amount, price.product_currency
                )
                or None,
                payment_provider=PAYMENT_PROVIDER,
            )
        except KeyError as exc:
            logger.warning(
                "Paystack initialization response for org %s is missing %s",
                org_id,
                exc,
            )
            raise CheckoutRejectedException(
                CheckoutReason.PROVIDER_UNAVAILABLE,
                "Our payment provider returned an incomplete response, so no "
                "payment was started. Please try again.",
                status_code=503,
            ) from exc

    @staticmethod
    def _unverified_response(
        reference: str,
        data: dict[str, Any],
        reason: str,
        message: str,
    ) -> VerifyTransactionResponse:
        """A payment the provider has not confirmed, described honestly.

        Returned rather than raised, because these are ordinary outcomes of a
        payment attempt (pending, declined, cancelled) rather than rejected
        requests: the checkout needs a shape it can render, and the plan stays
        whatever it already was.
        """
        return VerifyTransactionResponse(
            verified=False,
            plan=_normalized_plan(data),
            reference=str(data.get("reference") or reference),
            currency=str(data.get("currency") or "").upper() or None,
            amount_minor=int(data["amount"]) if data.get("amount") else None,
            reason=reason,
            reason_message=message,
        )

    async def verify_transaction(
        self,
        session: AsyncSession,
        reference: str,
        caller_org_id: uuid.UUID | None = None,
        user_id: uuid.UUID | None = None,
    ) -> VerifyTransactionResponse:
        """Confirm a payment with Paystack and activate it — or say why not.

        The browser never decides anything here: the client supplies only a
        reference, and every other fact (what was bought, for how long, for how
        much, in which currency, by which organization) is read from Paystack's
        own answer and from RELIASTRA's published pricing. A successful
        `onSuccess` callback in the popup is a hint to call this endpoint,
        never proof of payment — proof is the provider's `status`, `amount`
        and `currency` over TLS, from a server.

        Every rejection carries a :class:`CheckoutReason` slug so the checkout
        can show a specific, actionable state instead of relaying a provider
        error string to a customer.
        """
        try:
            result = await self.client.verify_transaction(reference)
        except httpx.HTTPStatusError as exc:
            # A 404 is an answer, not an outage: the gateway looked up the
            # reference and has no such transaction. Classifying it as
            # "we could not reach the provider" would send the customer away to
            # wait for a confirmation that will never come, when the truth is
            # that there is nothing to confirm — and the reference to check.
            if exc.response.status_code == 404:
                logger.info(
                    "Paystack has no transaction for reference %s (404 from the "
                    "provider); reporting it as not found rather than unavailable",
                    reference,
                )
                raise CheckoutRejectedException(
                    CheckoutReason.NOT_FOUND,
                    "We could not find a payment with that reference at our "
                    "provider, so nothing has been applied. Check the reference, "
                    "and if you paid, send it to billing@reliastra.com.",
                    status_code=409,
                    extra={"reference": reference},
                ) from exc
            raise CheckoutRejectedException(
                CheckoutReason.VERIFICATION_UNAVAILABLE,
                "We could not confirm your payment with our provider yet. If "
                "you completed the charge it is not lost — we verify every "
                "payment automatically and will activate your plan. Please "
                "check back in a few minutes.",
                status_code=503,
                extra={"reference": reference},
            ) from exc
        except httpx.HTTPError as exc:
            # Deliberately *not* "your payment failed". The customer may well
            # have paid; the truth is that RELIASTRA cannot confirm it right
            # now. Telling them otherwise would have them retry the charge.
            logger.warning("Paystack verification failed for %s: %s", reference, exc)
            raise CheckoutRejectedException(
                CheckoutReason.VERIFICATION_UNAVAILABLE,
                "We could not confirm your payment with our provider yet. If "
                "you completed the charge it is not lost — we verify every "
                "payment automatically and will activate your plan. Please "
                "check back in a few minutes.",
                status_code=503,
                extra={"reference": reference},
            ) from exc

        data = result.get("data") if isinstance(result.get("data"), dict) else {}
        provider_status = str(data.get("status") or "").strip().lower()
        if not result.get("status") or provider_status != "success":
            # Distinguish "still pending / awaiting authentication" from
            # "declined", because one has an action and the other does not.
            if provider_status in {"pending", "failed", ""} and not result.get("status"):
                raise CheckoutRejectedException(
                    CheckoutReason.NOT_FOUND,
                    "We could not find that payment on our account. If you "
                    "were charged, contact billing@reliastra.com with the "
                    "reference below.",
                    extra={"reference": reference},
                )
            if provider_status == "pending":
                return self._unverified_response(
                    reference,
                    data,
                    CheckoutReason.PENDING,
                    "Your payment is still being processed by your bank. "
                    "Nothing further is needed from you — we activate your "
                    "plan as soon as it settles.",
                )
            if provider_status in {"failed", "abandoned"}:
                return self._unverified_response(
                    reference,
                    data,
                    CheckoutReason.DECLINED,
                    "Your payment was not completed. No charge was made to "
                    "your card — you can try again, or use a different card.",
                )
            return self._unverified_response(
                reference,
                data,
                CheckoutReason.NOT_PAID,
                "We have not received this payment yet. If you completed the "
                "charge it may still be settling; we activate your plan "
                "automatically once it does.",
            )

        metadata = transaction_metadata(data.get("metadata"))
        org_id_raw = metadata.get("org_id")
        if not org_id_raw:
            logger.warning(
                "Verified transaction %s has no organization metadata", reference
            )
            raise CheckoutRejectedException(
                CheckoutReason.ORG_MISMATCH,
                "We could not match this payment to a RELIASTRA workspace. "
                "Contact billing@reliastra.com with the reference below and "
                "we will apply it to the right account.",
                extra={"reference": reference},
            )
        try:
            org_id = uuid.UUID(str(org_id_raw))
        except ValueError as exc:
            # A malformed organization id is a provider-response integrity
            # problem, not something the customer can fix: log the detail, give
            # them the same "contact billing" path as an unmatched payment.
            logger.warning(
                "Transaction %s carries unparseable org_id %r", reference, org_id_raw
            )
            raise CheckoutRejectedException(
                CheckoutReason.ORG_MISMATCH,
                "We could not match this payment to a RELIASTRA workspace. "
                "Contact billing@reliastra.com with the reference below.",
                extra={"reference": reference},
            ) from exc

        # A member of organization B must not be able to trigger
        # provisioning for organization A's payment reference.
        if caller_org_id is not None and org_id != caller_org_id:
            logger.warning(
                "Blocked cross-organization verification: reference %s belongs "
                "to %s, requested by %s",
                reference,
                org_id,
                caller_org_id,
            )
            # 403, and worded to say no more than "not yours": the response must
            # not confirm that the reference exists somewhere else, which would
            # turn this endpoint into a way to enumerate other organizations'
            # payments. The reason slug still lets the checkout explain that
            # nothing was applied and who to contact.
            raise CheckoutRejectedException(
                CheckoutReason.ORG_MISMATCH,
                "This payment cannot be matched to your RELIASTRA workspace, so "
                "nothing has been applied. If you paid, send the reference to "
                "billing@reliastra.com and we will apply it to the right account.",
                status_code=403,
            )
        # Channel policy: a global RELIASTRA checkout opens card rails only, so
        # a payment reporting a different rail did not come from this checkout.
        # Accepting it would let a locally-restricted settlement (a Nigerian
        # USSD or bank-transfer payment arranged outside the product) activate a
        # worldwide subscription, which is the bypass this guard exists to stop.
        channel_ok, channel_reason = settled_channel_is_acceptable(data.get("channel"))
        if not channel_ok:
            logger.warning(
                "Rejected verification for reference %s: %s", reference, channel_reason
            )
            raise CheckoutRejectedException(
                CheckoutReason.CHANNEL_POLICY,
                "This payment arrived through a method RELIASTRA's global "
                "checkout does not use, so it has not been applied "
                "automatically. Contact billing@reliastra.com and we will "
                "reconcile it.",
                status_code=409,
                extra={"reference": reference},
            )

        plan = _normalized_plan(data)
        billing_interval = _billing_interval(data)

        # Integrity check: the collected amount must cover the PAYMENT price of
        # the plan + billing interval the transaction claims to buy. This
        # prevents both a tampered/undersized charge from unlocking a higher
        # tier AND the historical bug where an annual checkout silently billed
        # the monthly amount.
        expected_price = _price_for(plan, billing_interval)
        expected_amount = expected_price.payment_amount
        collected = data.get("amount")
        if expected_amount is None:
            raise ValidationException(
                f"Plan '{plan}' is not available for self-serve checkout"
            )
        # Step 1 — CURRENCY. The expected amount is denominated in minor units
        # of the processing currency, so the integer comparison below is
        # meaningless until the denomination is known to match. A multi-currency
        # Paystack account can settle the same nominal amount in a far weaker
        # currency (3900 NGN is about $2.50, not the $39 Pro plan) and clear an
        # amount-only check. Checkout always initializes in the resolved
        # payment currency, so anything else did not come from our checkout.
        #
        # A MISSING currency is rejected too: defaulting it to the expected
        # value would let an omitted field pass the very check it must face.
        expected_currency = payment_currency()
        raw_currency = data.get("currency")
        collected_currency = str(raw_currency).strip().upper() if raw_currency else ""
        if collected_currency != expected_currency:
            logger.warning(
                "Rejected transaction %s: currency %r != expected %r",
                reference,
                collected_currency or None,
                expected_currency,
            )
            raise CheckoutRejectedException(
                CheckoutReason.CURRENCY_MISMATCH,
                f"The payment currency does not match this plan's billing "
                f"currency: it was collected in "
                f"{collected_currency or 'an unknown currency'}, but RELIASTRA "
                f"bills this plan in {expected_currency}, so it has not been "
                f"applied automatically. Contact billing@reliastra.com and we "
                f"will sort it out.",
                status_code=409,
                extra={"reference": reference},
            )

        # Step 2 — AMOUNT, now that both sides are in the same minor units.
        # Integer comparison only; never floats for money.
        if collected is None:
            raise ValidationException("Transaction is missing a collected amount")
        try:
            collected_minor = int(collected)
        except (TypeError, ValueError) as exc:
            raise ValidationException("Transaction amount is not an integer") from exc
        if collected_minor < expected_amount:
            logger.warning(
                "Rejected transaction %s: collected %s < expected %s (%s)",
                reference,
                collected_minor,
                expected_amount,
                expected_currency,
            )
            raise CheckoutRejectedException(
                CheckoutReason.AMOUNT_MISMATCH,
                "The amount collected does not cover the price of this plan, "
                "so it has not been applied automatically. Contact "
                "billing@reliastra.com and we will reconcile it.",
                status_code=409,
                extra={"reference": reference},
            )

        paid_at = _parse_datetime(data.get("paid_at"))

        org = await self.repository.get_org(session, org_id)
        if not org:
            raise ResourceNotFoundException("Organization not found")

        customer = data.get("customer")
        customer = customer if isinstance(customer, dict) else {}
        customer_code = customer.get("customer_code")
        subscription = await self.repository.get_subscription(session, org_id)

        # Replay protection. The subscription row persists which reference
        # provisioned it (provider_subscription_id) and when that payment
        # was made (current_period_start). Re-verifying the SAME reference
        # stays idempotent; presenting any OTHER reference whose payment is
        # not newer than the already-applied one is a replay — e.g. re-using
        # an old reference after cancellation to restore the paid plan for
        # free.
        if (
            subscription is not None
            and subscription.current_period_start is not None
            and paid_at is not None
            and str(subscription.provider_subscription_id or "") != reference
            and paid_at <= subscription.current_period_start
        ):
            logger.warning(
                "Rejected replayed billing verification for reference %s (org %s)",
                reference,
                org_id,
            )
            return VerifyTransactionResponse(
                verified=False,
                plan=subscription.plan or Plan.FREE.value,
                reference=reference,
                reason=CheckoutReason.REPLAYED,
            )

        # A second, *newer* payment for a period already covered is not a
        # replay — the customer really paid twice, usually by refreshing and
        # retrying. Refusing it would strand their money; ignoring it would be
        # a surprise on the invoice. So it is applied and stated plainly.
        duplicate_within_period = bool(
            subscription is not None
            and subscription.status == "active"
            and subscription.current_period_end is not None
            and paid_at is not None
            and str(subscription.provider_subscription_id or "") != reference
            and subscription.current_period_end > paid_at
        )
        if duplicate_within_period:
            logger.warning(
                "Duplicate payment for org %s within the active period "
                "(reference %s); applied and flagged for support",
                org_id,
                reference,
            )

        # Was this payment already the thing that made the organization paid?
        # Read before the update below, so it describes the state this call
        # found rather than the state it created. A customer who reloads the
        # confirmation page re-verifies the same reference, and telling them the
        # plan "was activated" again would imply something changed a second time
        # — the answer they need is that the same payment is still applied.
        already_applied = bool(
            subscription is not None
            and subscription.status == "active"
            and subscription.plan == plan
            and str(subscription.provider_subscription_id or "") == reference
        )

        values = {
            "plan": plan,
            "status": "active",
            "provider_customer_id": customer_code,
            "provider_subscription_id": str(data.get("subscription_code") or reference),
            "current_period_start": paid_at,
            "current_period_end": _resolve_period_end(
                paid_at,
                billing_interval,
                _parse_datetime(data.get("next_payment_date")),
            ),
            "billing_interval": billing_interval,
        }
        if subscription:
            await self.repository.update_subscription(session, subscription, **values)
        else:
            await self.repository.create_subscription(session, org_id, **values)

        from app.modules.organizations.repository import OrganizationRepository

        # Evaluation -> paid transition: paid plan becomes authoritative and the
        # evaluation is marked converted so it never re-activates. No conflicting
        # evaluation state: effective entitlements now follow the paid plan.
        await OrganizationRepository.update(
            session, org, plan=plan, evaluation_status="converted"
        )

        # Persist the charge as the provider reported it. This is the
        # permanent record of "what was actually paid": currency-explicit
        # minor units from Paystack's own response, alongside the USD
        # product price the checkout quoted. Receipts and the billing page
        # read history from here, so a price-list change can never rewrite a
        # past payment. Idempotent on (provider, reference).
        try:
            await self.repository.record_transaction(
                session,
                organization_id=org_id,
                reference=str(data.get("reference") or reference),
                email=customer.get("email"),
                plan=plan,
                billing_interval=billing_interval,
                product_currency=expected_price.product_currency,
                product_amount_minor=expected_price.product_amount,
                charged_currency=collected_currency,
                charged_amount_minor=int(collected_minor),
                # Who authorized the purchase (never card data) and when
                # RELIASTRA confirmed it server-side. ``verified_at`` is kept
                # distinct from ``paid_at`` on purpose: the provider's
                # timestamp is when money moved, ours is when this record was
                # established as verified — the two differ under webhook retry
                # and are both needed in a dispute.
                user_id=_optional_uuid(metadata.get("actor_user_id")) or user_id,
                verified_at=datetime.now(timezone.utc),
                duplicate=duplicate_within_period,
                paid_at=paid_at,
                period_start=_parse_datetime(data.get("transaction_date")) or paid_at,
                period_end=_parse_datetime(data.get("next_payment_date")),
                provider_metadata={
                    key: data.get(key)
                    for key in (
                        "id",
                        "domain",
                        "channel",
                        "gateway_reference",
                        "status",
                        "transaction_date",
                    )
                    if data.get(key) is not None
                },
            )
        except Exception:
            # The charge and provisioning are done; a record-keeping failure
            # must not turn a successful payment into a failed verification.
            # Logged loudly because reconciliation depends on this table.
            logger.exception(
                "Failed to persist billing transaction for reference %s", reference
            )

        # Funnel analytics: this checkout lead converted. Single choke point
        # covers both the frontend verify call and the charge.success webhook.
        from app.modules.analytics.service import analytics_service

        await analytics_service.record_checkout_converted(str(org_id))

        # Partner network: a verified, collected payment is the only thing
        # that creates commission. We pass the amount Paystack reports as
        # actually collected, never a plan list price. Both the direct
        # verify call and the `charge.success` webhook land here, and the
        # commission service is idempotent on the payment reference, so a
        # duplicate delivery cannot pay a partner twice.
        await self._record_partner_commission(session, org_id, data, reference)

        # Transactional email: subscription confirmation + receipt. Best-effort
        # and exactly-once per payment reference (a webhook retry and the
        # frontend verify call land in this same method).
        await self._notify_payment_succeeded(
            session,
            org=org,
            payment=PaymentSummary(
                plan=plan,
                billing_interval=billing_interval,
                amount_minor=int(collected_minor),
                currency=collected_currency or expected_currency,
                reference=reference,
                paid_at=paid_at,
                period_start=_parse_datetime(data.get("transaction_date")) or paid_at,
                period_end=_parse_datetime(data.get("next_payment_date")),
            ),
        )

        settled_currency = collected_currency or expected_currency
        return VerifyTransactionResponse(
            verified=True,
            plan=plan,
            billing_interval=billing_interval,
            # The confirmation screen needs the plan's *customer* name and the
            # period it bought, and must not re-derive either from a local
            # dictionary — so both are answered here, beside the figures.
            display_plan=PLAN_DISPLAY_NAMES.get(plan, plan.title()),
            period_word="year" if billing_interval == ANNUAL_INTERVAL else "month",
            activated=not already_applied,
            duplicate_payment=duplicate_within_period,
            reason=CheckoutReason.DUPLICATE_PAYMENT if duplicate_within_period else None,
            reference=reference,
            currency=settled_currency,
            amount_minor=int(collected_minor),
            amount_display=format_money(int(collected_minor), settled_currency),
            # Product side of the transparency triple, from the same figures
            # persisted on the transaction — the confirmation screen restates
            # the deal, not a fresh calculation.
            product_currency=expected_price.product_currency,
            product_amount_minor=expected_price.product_amount,
            product_price_display=format_money(
                expected_price.product_amount, expected_price.product_currency
            )
            or None,
            payment_provider=PAYMENT_PROVIDER,
        )

    async def _notify_payment_succeeded(
        self, session: AsyncSession, *, org, payment: PaymentSummary
    ) -> None:
        """Send confirmation + receipt once per payment reference.

        Never raises: the customer has already paid, and a broken SMTP socket
        must not turn a successful charge into a failed verification.
        """
        try:
            if payment.reference:
                from app.infrastructure.redis_client import safe_redis_claim

                claimed = await safe_redis_claim(
                    f"billing:receipt_sent:{payment.reference}", ex=30 * 24 * 3600
                )
                if claimed is False:
                    return
            from app.modules.organizations.repository import OrganizationRepository
            from app.modules.users.repository import UserRepository

            members = await OrganizationRepository.list_members(session, org.id)
            owner = next((m for m in members if m.role == "owner"), None)
            user = await UserRepository.get_by_id(session, owner.user_id) if owner else None
            if user is None or not user.email:
                logger.info(
                    "No owner email for org %s — payment emails skipped", org.id
                )
                return
            await send_subscription_confirmed_email(
                to_email=user.email,
                user_name=user.full_name or user.email.split("@")[0],
                org_name=org.name,
                payment=payment,
            )
            await send_payment_receipt_email(
                to_email=user.email,
                user_name=user.full_name or user.email.split("@")[0],
                org_name=org.name,
                payment=payment,
            )
        except Exception:
            logger.exception("Billing notification failed for reference %s", payment.reference)

    @staticmethod
    async def _record_partner_commission(
        session: AsyncSession,
        org_id: uuid.UUID,
        data: dict[str, Any],
        reference: str,
    ) -> None:
        """Convert a verified payment into a partner commission.

        Failures here must never fail the payment itself — the customer has
        already paid and their plan must be provisioned.
        """
        try:
            collected = data.get("amount")
            if not collected:
                return

            from app.modules.partners.commissions import commission_service

            paid_at = _parse_datetime(data.get("paid_at"))

            await commission_service.record_payment(
                session,
                organization_id=org_id,
                collected_minor=int(collected),
                currency=str(data.get("currency") or "USD").upper()[:3],
                payment_reference=reference,
                paid_at=paid_at,
                payment_provider="paystack",
            )
        except Exception:
            logger.exception(
                "Partner commission processing failed for payment %s",
                reference,
            )

    @staticmethod
    def _webhook_event_id(payload: dict[str, Any]) -> str | None:
        """Stable per-event identifier for idempotency (FIX 31)."""
        data = payload.get("data")
        data = data if isinstance(data, dict) else {}
        event_type = str(payload.get("event", ""))
        event_id = (
            data.get("id")
            or data.get("event_id")
            or data.get("reference")
            or data.get("subscription_code")
        )
        if not event_type or not event_id:
            return None
        return f"{event_type}:{event_id}"

    async def _claim_webhook_event(self, event_id: str) -> bool | None:
        """Claim *event_id* for processing. Tri-state — see the return values.

        Uses a Redis SET-NX with a 24h TTL so Paystack retries (which resend
        the same event) never double-process ``charge.success``.

        Returns:
            True  — claimed; this delivery should be processed.
            False — the event was already processed; skip it.
            None  — the idempotency store is unreachable, so we cannot tell.

        ``None`` is deliberately NOT collapsed into either bool. The caller
        must decide, because both defaults are wrong: treating it as a
        duplicate drops the payment, and treating it as claimed processes a
        money event with no duplicate protection at all.
        """
        from app.infrastructure.redis_client import safe_redis_claim

        return await safe_redis_claim(f"paystack:event:{event_id}", ex=24 * 3600)

    async def handle_webhook(
        self,
        session: AsyncSession,
        payload: dict[str, Any],
        signature: str | None = None,
        raw_body: bytes | None = None,
    ) -> PaystackWebhookResponse:
        if not signature:
            raise UnauthorizedException("Missing Paystack webhook signature")
        if not raw_body:
            raise UnauthorizedException("Missing raw request body")
        if not settings.PAYSTACK_SECRET_KEY:
            raise UnauthorizedException("Paystack webhook secret is not configured")

        expected = hmac.new(
            settings.PAYSTACK_SECRET_KEY.encode("utf-8"),
            raw_body,
            hashlib.sha512,
        ).hexdigest()
        if not hmac.compare_digest(expected, signature):
            raise UnauthorizedException("Invalid Paystack webhook signature")

        event_type = str(payload.get("event", ""))
        data = payload.get("data")
        data = data if isinstance(data, dict) else {}
        logger.info("Received verified Paystack webhook: %s", event_type)

        # FIX 31: idempotency — skip events already processed in the last 24h.
        event_id = self._webhook_event_id(payload)
        if event_id:
            claimed = await self._claim_webhook_event(event_id)
            if claimed is False:
                logger.info("Skipping duplicate Paystack webhook event %s", event_id)
                return PaystackWebhookResponse(received=True, event_type=event_type)
            if claimed is None:
                # The idempotency store is down, so this delivery cannot be
                # de-duplicated. Refuse it instead of guessing.
                #
                # Answering 200 would permanently tell Paystack the event was
                # accepted, and every unprocessed payment, refund and
                # chargeback would be lost with no way to replay it. A 503
                # keeps the event in Paystack's retry queue until the store
                # recovers. The customer-facing /billing/verify path also
                # provisions independently, so this defers work rather than
                # losing it.
                logger.error(
                    "Paystack webhook idempotency store unavailable — refusing "
                    "event %s (type=%s) so Paystack retries it",
                    event_id,
                    event_type,
                    extra={"event_id": event_id, "event_type": event_type},
                )
                raise ServiceUnavailableException(
                    "Webhook idempotency store unavailable; please retry"
                )

        if event_type == "charge.success" and data.get("reference"):
            await self.verify_transaction(session, str(data["reference"]))
        elif event_type == "subscription.create":
            await self._upsert_webhook_subscription(session, data)
        elif event_type in {"subscription.disable", "subscription.not_renew"}:
            await self._disable_webhook_subscription(session, data)
            # Churn stops future partner accrual but never reverses
            # commissions on revenue that was collected and kept.
            await self._handle_partner_churn(session, data)
        elif event_type in {"refund.processed", "charge.refunded"}:
            await self._reverse_partner_commissions(session, data, "refund")
            # The persisted transaction record must tell the truth about the
            # money: a refunded payment is flagged in the history the
            # customer sees on the billing page.
            await self._mark_transaction_status(session, data, "refunded")
            # A refunded payment must not keep the paid plan active. Mirror
            # the churn behaviour: mark the subscription inactive and drop
            # the organization back to the free plan.
            await self._disable_webhook_subscription(session, data)
        elif event_type in {"charge.dispute.create", "charge.dispute.remind"}:
            await self._reverse_partner_commissions(session, data, "chargeback")
            await self._mark_transaction_status(session, data, "disputed")
            await self._disable_webhook_subscription(session, data)

        return PaystackWebhookResponse(received=True, event_type=event_type)

    @staticmethod
    async def _mark_transaction_status(
        session: AsyncSession, data: dict[str, Any], status: str
    ) -> None:
        """Flag a persisted transaction on refund/dispute webhook events."""
        try:
            transaction = data.get("transaction")
            transaction = transaction if isinstance(transaction, dict) else {}
            reference = (
                data.get("transaction_reference")
                or data.get("reference")
                or transaction.get("reference")
            )
            if not reference:
                return
            await BillingRepository.mark_transaction_status(
                session, reference=str(reference), status=status
            )
        except Exception:
            logger.exception("Billing transaction status update failed (%s)", status)

    @staticmethod
    async def _reverse_partner_commissions(
        session: AsyncSession, data: dict[str, Any], reason: str
    ) -> None:
        """Reverse partner commissions after a refund or chargeback.

        The original commission rows are never deleted — their status is set
        to ``reversed``.
        """
        try:
            transaction = data.get("transaction")
            transaction = transaction if isinstance(transaction, dict) else {}
            reference = (
                data.get("transaction_reference")
                or data.get("reference")
                or transaction.get("reference")
            )
            if not reference:
                logger.info("Ignoring %s event without a transaction reference", reason)
                return

            from app.modules.partners.commissions import commission_service

            count = await commission_service.reverse_by_reference(
                session,
                payment_reference=str(reference),
                reason=reason,
            )
            if count:
                logger.info(
                    "Reversed %d partner commissions for %s (%s)",
                    count,
                    reference,
                    reason,
                )
        except Exception:
            logger.exception("Partner commission reversal failed for %s", reason)

    @staticmethod
    async def _handle_partner_churn(
        session: AsyncSession, data: dict[str, Any]
    ) -> None:
        try:
            customer = data.get("customer")
            customer = customer if isinstance(customer, dict) else {}
            customer_code = customer.get("customer_code")
            if not customer_code:
                return

            from app.modules.billing.repository import BillingRepository
            from app.modules.partners.commissions import commission_service

            org = await BillingRepository.get_org_by_provider_customer(
                session, str(customer_code)
            )
            if org is None:
                return
            await commission_service.handle_churn(session, organization_id=org.id)
        except Exception:
            logger.exception("Partner churn handling failed")

    async def _upsert_webhook_subscription(
        self, session: AsyncSession, data: dict[str, Any]
    ) -> None:
        metadata = transaction_metadata(data.get("metadata"))
        org_id_raw = metadata.get("org_id")
        if not org_id_raw:
            logger.info("Ignoring subscription event without org_id metadata")
            return
        try:
            org_id = uuid.UUID(str(org_id_raw))
        except ValueError:
            logger.warning("Ignoring subscription event with invalid org_id")
            return
        org = await self.repository.get_org(session, org_id)
        if not org:
            logger.info("Ignoring subscription event for unknown org %s", org_id)
            return

        customer = data.get("customer")
        customer = customer if isinstance(customer, dict) else {}
        values = {
            "plan": _normalized_plan(data),
            "status": str(data.get("status") or "active"),
            "provider_customer_id": customer.get("customer_code"),
            "provider_subscription_id": data.get("subscription_code"),
            "current_period_start": _parse_datetime(data.get("createdAt")),
            "current_period_end": _resolve_period_end(
                _parse_datetime(data.get("createdAt")),
                _billing_interval(data),
                _parse_datetime(data.get("next_payment_date")),
            ),
            "billing_interval": _billing_interval(data),
        }
        subscription = await self.repository.get_subscription(session, org_id)
        if subscription:
            await self.repository.update_subscription(session, subscription, **values)
        else:
            await self.repository.create_subscription(session, org_id, **values)

        from app.modules.organizations.repository import OrganizationRepository

        await OrganizationRepository.update(
            session, org, plan=values["plan"], evaluation_status="converted"
        )

    async def _disable_webhook_subscription(
        self, session: AsyncSession, data: dict[str, Any]
    ) -> None:
        customer = data.get("customer")
        customer = customer if isinstance(customer, dict) else {}
        customer_code = customer.get("customer_code")
        if not customer_code:
            return
        org = await self.repository.get_org_by_provider_customer(
            session, str(customer_code)
        )
        if not org:
            return
        subscription = await self.repository.get_subscription(session, org.id)
        if subscription:
            await self.repository.update_subscription(
                session, subscription, status="inactive"
            )

        from app.modules.organizations.repository import OrganizationRepository

        # Refund/churn/disable returns to Free; evaluation is expired and will
        # not re-activate. Data is preserved, limits fall back.
        await OrganizationRepository.update(
            session, org, plan=Plan.FREE.value, evaluation_status="expired"
        )


billing_service = BillingService()
