'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '@/lib/utils';

const ease = [0.25, 0.1, 0.25, 1] as const;

const TABS = ['SaaS Teams', 'Agencies', 'DevOps'] as const;
type TabKey = (typeof TABS)[number];

const TAB_CONTENT: Record<TabKey, { headline: string; body: string; visual: React.ReactNode }> = {
  'SaaS Teams': {
    headline: 'Protect Your SLA Commitments',
    body: 'Your customers pay for 99.9% uptime. When a vendor like PagerDuty or Stripe drops the ball, your SLA is on the line: not theirs. Reliastra gives you the independent evidence to claim vendor SLA credits and protect your margins.',
    visual: (
      <div className="space-y-3 rounded-2xl border border-[#E4E4E7] bg-white p-6 dark:border-white/10 dark:bg-[#131318]">
        <p className="text-xs font-semibold uppercase tracking-widest text-[#A1A1AA] dark:text-[#71717A]">
          What you can show a vendor
        </p>
        <p className="text-sm leading-relaxed text-[#52525B] dark:text-[#A1A1AA]">
          Independent check times, HTTP results, and latency from Reliastra probes — not a credit estimate.
          The vendor still decides whether to pay.
        </p>
        <button
          onClick={() => scrollToId('live')}
          className="inline-block text-sm font-semibold text-[#0891B2] hover:underline dark:text-[#22D3EE]"
        >
          See live public checks
        </button>
      </div>
    ),
  },
  Agencies: {
    headline: 'Keep Clients. Keep Revenue.',
    body: 'When a vendor outage affects your client’s site, they don’t care whose fault it is: they care that it’s down. Reliastra gives you the evidence report to show exactly what happened, protecting your relationship and your invoice.',
    visual: (
      <div className="overflow-hidden rounded-2xl border border-[#E4E4E7] bg-[#F8F9FA] dark:border-white/10 dark:bg-[#1A1A20]">
        <div className="flex items-center gap-2 border-b border-[#E4E4E7] bg-white px-4 py-3 dark:border-white/10 dark:bg-[#131318]">
          <div className="flex gap-1.5">
            <div className="h-[10px] w-[10px] rounded-full bg-[#EF4444]" />
            <div className="h-[10px] w-[10px] rounded-full bg-[#F59E0B]" />
            <div className="h-[10px] w-[10px] rounded-full bg-[#22C55E]" />
          </div>
          <div className="flex-1 text-center">
            <span className="font-mono text-xs text-[#A1A1AA] dark:text-[#71717A]">
              reliastra.com/reports/agency-share
            </span>
          </div>
        </div>
        <div className="space-y-3 p-5">
          <div className="flex items-center gap-2 mb-4">
            <div className="flex h-6 w-6 items-center justify-center rounded bg-[#0891B2]/10">
              <span className="text-[10px] font-bold text-[#0891B2] dark:text-[#22D3EE]">R</span>
            </div>
            <span className="text-sm font-semibold text-[#09090B] dark:text-[#FAFAFA]">
              Reliastra Report
            </span>
            <span className="ml-auto rounded-full bg-[#16A34A]/10 px-2 py-0.5 text-[10px] font-medium text-[#16A34A] dark:text-[#22C55E]">
              Shared
            </span>
          </div>
          <p className="text-xs leading-relaxed text-[#52525B] dark:text-[#A1A1AA]">
            Prepared for: <span className="font-semibold text-[#09090B] dark:text-[#FAFAFA]">Acme Corp</span>
            <br />
            Incident: Third-party API degradation affecting checkout flow.
          </p>
          <div className="border-t border-[#E4E4E7] pt-3 text-xs text-[#A1A1AA] dark:border-white/10 dark:text-[#71717A]">
            Generated by Reliastra · Independent verification from 3 regions
          </div>
        </div>
      </div>
    ),
  },
  DevOps: {
    headline: 'Validate What You Can’t See.',
    body: 'You already have Datadog, Grafana, and PagerDuty. But they only see inside your infrastructure. Reliastra adds the external layer: monitoring vendors from the outside in, so you can validate what’s really happening.',
    visual: (
      <div className="space-y-3">
        <div className="rounded-xl border border-[#E4E4E7] bg-[#F8F9FA] p-4 dark:border-white/10 dark:bg-[#1A1A20]">
          <p className="mb-2 text-[10px] font-semibold uppercase tracking-widest text-[#A1A1AA] dark:text-[#71717A]">
            Internal (Datadog)
          </p>
          <div className="flex items-center gap-3">
            <div className="h-8 flex-1 overflow-hidden rounded bg-[#E4E4E7] dark:bg-white/10">
              <div className="flex h-full w-[85%] items-center rounded bg-[#16A34A]/20 px-2">
                <span className="text-[10px] font-mono text-[#16A34A] dark:text-[#22C55E]">All green</span>
              </div>
            </div>
          </div>
          <p className="mt-1 text-[10px] text-[#A1A1AA] dark:text-[#71717A]">Your infra looks fine</p>
        </div>
        <div className="flex justify-center">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <path d="M12 5v14M5 12l7 7 7-7" stroke="#0891B2" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </div>
        <div className="rounded-xl border border-[#DC2626]/20 bg-[#F8F9FA] p-4 dark:border-[#F87171]/20 dark:bg-[#1A1A20]">
          <p className="mb-2 text-[10px] font-semibold uppercase tracking-widest text-[#A1A1AA] dark:text-[#71717A]">
            External (Reliastra)
          </p>
          <div className="flex items-center gap-3">
            <div className="h-8 flex-1 overflow-hidden rounded bg-[#E4E4E7] dark:bg-white/10">
              <div className="flex h-full w-[60%] items-center rounded bg-[#DC2626]/20 px-2">
                <span className="text-[10px] font-mono text-[#DC2626] dark:text-[#F87171]">Vendor degraded</span>
              </div>
            </div>
          </div>
          <p className="mt-1 text-[10px] text-[#52525B] dark:text-[#A1A1AA]">
            Independent probes can disagree with internal green dashboards
          </p>
        </div>
      </div>
    ),
  },
};

export function UseCasesSection() {
  const [activeTab, setActiveTab] = useState<TabKey>('SaaS Teams');
  const content = TAB_CONTENT[activeTab];

  return (
    <section className="bg-[#F8F9FA] py-32 dark:bg-[#131318]">
      <div className="mx-auto max-w-[1200px] px-6 md:px-12">
        <motion.div
          className="mx-auto mb-12 max-w-2xl text-center"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.6, ease }}
        >
          <p className="mb-4 text-xs font-semibold uppercase tracking-widest text-[#0891B2] dark:text-[#22D3EE]">
            USE CASES
          </p>
          <h2 className="text-3xl font-semibold tracking-tight text-[#09090B] dark:text-[#FAFAFA] sm:text-4xl">
            Built for teams that depend on vendors.
          </h2>
        </motion.div>

        <motion.div
          className="mb-16 flex justify-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.6, delay: 0.1, ease }}
        >
          <div className="inline-flex rounded-full border border-[#E4E4E7] bg-white p-1 dark:border-white/10 dark:bg-[#1A1A20]">
            {TABS.map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={cn(
                  'relative min-h-[44px] rounded-full px-6 py-2.5 text-sm font-medium transition-colors duration-200',
                  activeTab === tab
                    ? 'text-white dark:text-[#0A0A0F]'
                    : 'text-[#52525B] hover:text-[#09090B] dark:text-[#A1A1AA] dark:hover:text-white'
                )}
                aria-pressed={activeTab === tab}
              >
                {activeTab === tab && (
                  <motion.div
                    layoutId="activeTabBg"
                    className="absolute inset-0 rounded-full bg-[#0A0A0F] dark:bg-white"
                    transition={{ type: 'spring', stiffness: 400, damping: 30 }}
                  />
                )}
                <span className="relative z-10">{tab}</span>
              </button>
            ))}
          </div>
        </motion.div>

        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            className="grid grid-cols-1 items-center gap-16 lg:grid-cols-2"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.4, ease }}
          >
            <div>
              <h3 className="mb-4 text-2xl font-semibold text-[#09090B] dark:text-[#FAFAFA]">
                {content.headline}
              </h3>
              <p className="leading-relaxed text-[#52525B] dark:text-[#A1A1AA]">{content.body}</p>
            </div>
            <div className="flex justify-center lg:justify-end">{content.visual}</div>
          </motion.div>
        </AnimatePresence>
      </div>
    </section>
  );
}
