import { SITE_URL } from '@/lib/seo';

/**
 * Per-paper social artwork.
 *
 * The site-wide `/opengraph-image.png` is a brand card: wordmark, tagline,
 * domain. It is the right image for a product page. For a research paper it is
 * the wrong one - a shared link carries no title, no byline and no finding, so
 * the platform invents a snippet from whatever it can find.
 *
 * Papers that have their own card list it here. The PNGs are generated by
 * `frontend/scripts/generate-paper-og-image.mjs`, which reads the title,
 * category, reading time and byline from the page's own `TechArticle` JSON-LD,
 * so a card cannot quietly disagree with the record it illustrates. Both the
 * SVG source and the 1200x630 PNG are committed, because production must serve
 * them without runtime image rendering.
 *
 * A paper with no entry here falls back to the site-wide card. That is the
 * honest default: a generic brand card is better than no card, and a card whose
 * content was typed by hand next to a record it can drift from is worse than
 * both.
 */
export const PAPER_OG_IMAGES: Record<string, { path: string; alt: string }> = {
  'aws-iam-policy-evaluation-order': {
    path: '/social/research/aws-iam-policy-evaluation-order-og.png',
    alt:
      'RELIASTRA Research card for "AWS IAM policy evaluation logic: identity vs resource". ' +
      'The seven stages of the documented single-account procedure, each labelled with its ' +
      'algebraic role - one short-circuit, four ceilings, two grants - with the byline ' +
      'Adeshina Emmanuel, AI Infrastructure Security Engineer.',
  },
};

/** The Open Graph / Twitter image for a research paper. */
export function researchSocialImage(slug: string, title: string) {
  const card = PAPER_OG_IMAGES[slug];
  if (!card) {
    return {
      url: `${SITE_URL}/opengraph-image.png`,
      width: 1200,
      height: 630,
      alt: title,
    };
  }
  return { url: `${SITE_URL}${card.path}`, width: 1200, height: 630, alt: card.alt };
}
