"""app.core.commercial_terms — backward-compatibility alias.

Canonical home: ``app.modules.billing.commercial_terms``
Moved during the platform redesign. New code must import from the canonical
path; this module re-exports the exact same objects and is covered by the
import-parity test (``tests/unit/test_import_parity.py``).
"""

from app.modules.billing.commercial_terms import (  # noqa: F401
    BILLING_EMAIL,
    BILLING_PATH,
    CANCELLATION_TAKES_EFFECT,
    PAYMENT_REQUIRED_BEFORE_TRIAL,
    PRIVACY_PATH,
    REFUND_PERIOD_DAYS,
    REFUND_POLICY_PATH,
    SELLER_BRAND,
    SELLER_LEGAL_NAME,
    SELLER_SUPPORT_EMAIL,
    TERMS_PATH,
    TRIAL_DAYS,
    TRIAL_REQUIRES_PAYMENT,
    annotations,
    billing_contact,
    cancellation_after_effect,
    cancellation_summary,
    cancellation_versus_refund,
    checkout_what_you_buy,
    get_plan_price_usd,
    price_after_trial_summary,
    promotional_treatment,
    public_policy,
    refund_destination,
    refund_eligibility,
    refund_how_to_request,
    refund_period,
    refund_processing,
    refund_summary,
    settings,
    terms_acceptance_label,
    trial_end_summary,
    trial_summary,
    _pro_price,
)

__all__ = [
    "BILLING_EMAIL",
    "BILLING_PATH",
    "CANCELLATION_TAKES_EFFECT",
    "PAYMENT_REQUIRED_BEFORE_TRIAL",
    "PRIVACY_PATH",
    "REFUND_PERIOD_DAYS",
    "REFUND_POLICY_PATH",
    "SELLER_BRAND",
    "SELLER_LEGAL_NAME",
    "SELLER_SUPPORT_EMAIL",
    "TERMS_PATH",
    "TRIAL_DAYS",
    "TRIAL_REQUIRES_PAYMENT",
    "annotations",
    "billing_contact",
    "cancellation_after_effect",
    "cancellation_summary",
    "cancellation_versus_refund",
    "checkout_what_you_buy",
    "get_plan_price_usd",
    "price_after_trial_summary",
    "promotional_treatment",
    "public_policy",
    "refund_destination",
    "refund_eligibility",
    "refund_how_to_request",
    "refund_period",
    "refund_processing",
    "refund_summary",
    "settings",
    "terms_acceptance_label",
    "trial_end_summary",
    "trial_summary",

]
