"""app.core.payment_pricing — backward-compatibility alias.

Canonical home: ``app.modules.billing.pricing``
Moved during the platform redesign. New code must import from the canonical
path; this module re-exports the exact same objects and is covered by the
import-parity test (``tests/unit/test_import_parity.py``).
"""

from app.modules.billing.pricing import (  # noqa: F401
    ANNUAL,
    CURRENCY_NAMES,
    CURRENCY_NOTICES,
    CURRENCY_SYMBOLS,
    FX_REFERENCE_DISCLAIMER,
    MONTHLY,
    NGN_CURRENCY_NOTICE,
    PAYMENT_PROVIDER,
    PAYMENT_PROVIDER_DISPLAY,
    PLAN_AMOUNTS,
    PLAN_ANNUAL_AMOUNTS,
    PLAN_BILLING_AVAILABILITY,
    PLAN_PRICES_USD,
    PRODUCT_CURRENCY,
    PaymentPrice,
    PaymentPriceNotConfigured,
    annotations,
    checkout_amount,
    checkout_ready,
    converted_payment_amount,
    currency_info,
    currency_mismatch,
    currency_name,
    customer_currency_notice,
    dataclass,
    format_money,
    format_product_price,
    get_plan_annual_price_usd,
    logger,
    logging,
    minimum_product_amount,
    normalize_plan,
    payment_currency,
    resolve_payment_price,
    resolved_payment_amounts,
    self_serve_plans,
    settings,
    transparency_lines,
)

__all__ = [
    "ANNUAL",
    "CURRENCY_NAMES",
    "CURRENCY_NOTICES",
    "CURRENCY_SYMBOLS",
    "FX_REFERENCE_DISCLAIMER",
    "MONTHLY",
    "NGN_CURRENCY_NOTICE",
    "PAYMENT_PROVIDER",
    "PAYMENT_PROVIDER_DISPLAY",
    "PLAN_AMOUNTS",
    "PLAN_ANNUAL_AMOUNTS",
    "PLAN_BILLING_AVAILABILITY",
    "PLAN_PRICES_USD",
    "PRODUCT_CURRENCY",
    "PaymentPrice",
    "PaymentPriceNotConfigured",
    "annotations",
    "checkout_amount",
    "checkout_ready",
    "converted_payment_amount",
    "currency_info",
    "currency_mismatch",
    "currency_name",
    "customer_currency_notice",
    "dataclass",
    "format_money",
    "format_product_price",
    "get_plan_annual_price_usd",
    "logger",
    "logging",
    "minimum_product_amount",
    "normalize_plan",
    "payment_currency",
    "resolve_payment_price",
    "resolved_payment_amounts",
    "self_serve_plans",
    "settings",
    "transparency_lines",

]
