"""app.core.permissions — backward-compatibility alias.

Canonical home: ``app.platform.tenancy.roles``, ``app.platform.commercial.entitlements``
Moved during the platform redesign. New code must import from the canonical
path; this module re-exports the exact same objects and is covered by the
import-parity test (``tests/unit/test_import_parity.py``).
"""

from app.platform.tenancy.roles import (  # noqa: F401
    Enum,
    ForbiddenException,
    ROLE_HIERARCHY,
    Role,
    get_role_level,
    has_permission,
    require_permission,
)
from app.platform.commercial.entitlements import (  # noqa: F401
    CANONICAL_PLANS,
    EVALUATION_DAYS,
    EVALUATION_PLAN,
    LEGACY_PLAN_MAP,
    PLAN_AMOUNTS,
    PLAN_ANNUAL_AMOUNTS,
    PLAN_ANNUAL_PRICES_USD,
    PLAN_BILLING_AVAILABILITY,
    PLAN_CHECK_INTERVALS,
    PLAN_DEPENDENCY_LIMITS,
    PLAN_DESCRIPTIONS,
    PLAN_DISPLAY_NAMES,
    PLAN_FEATURES,
    PLAN_PRICES_USD,
    PLAN_RETENTION_DAYS,
    PLAN_TAGS,
    PLAN_TEAM_LIMITS,
    PUBLIC_PLAN_CATALOG,
    Plan,
    TRIAL_DAYS,
    TRIAL_PLAN,
    datetime,
    evaluation_days_remaining,
    get_dependency_limit,
    get_effective_entitlements,
    get_effective_plan,
    get_effective_plan_for_org,
    get_evaluation_status,
    get_min_check_interval,
    get_plan_annual_price_usd,
    get_plan_billing_availability,
    get_plan_display_name,
    get_plan_price_usd,
    get_retention_days,
    get_team_limit,
    is_custom_plan,
    is_enterprise_plan,
    is_evaluation_active,
    is_paid_plan,
    is_trial_active,
    is_valid_plan,
    normalize_plan,
    plan_allows_feature,
    timedelta,
    timezone,
    trial_days_remaining,
)

__all__ = [
    "CANONICAL_PLANS",
    "EVALUATION_DAYS",
    "EVALUATION_PLAN",
    "Enum",
    "ForbiddenException",
    "LEGACY_PLAN_MAP",
    "PLAN_AMOUNTS",
    "PLAN_ANNUAL_AMOUNTS",
    "PLAN_ANNUAL_PRICES_USD",
    "PLAN_BILLING_AVAILABILITY",
    "PLAN_CHECK_INTERVALS",
    "PLAN_DEPENDENCY_LIMITS",
    "PLAN_DESCRIPTIONS",
    "PLAN_DISPLAY_NAMES",
    "PLAN_FEATURES",
    "PLAN_PRICES_USD",
    "PLAN_RETENTION_DAYS",
    "PLAN_TAGS",
    "PLAN_TEAM_LIMITS",
    "PUBLIC_PLAN_CATALOG",
    "Plan",
    "ROLE_HIERARCHY",
    "Role",
    "TRIAL_DAYS",
    "TRIAL_PLAN",
    "datetime",
    "evaluation_days_remaining",
    "get_dependency_limit",
    "get_effective_entitlements",
    "get_effective_plan",
    "get_effective_plan_for_org",
    "get_evaluation_status",
    "get_min_check_interval",
    "get_plan_annual_price_usd",
    "get_plan_billing_availability",
    "get_plan_display_name",
    "get_plan_price_usd",
    "get_retention_days",
    "get_role_level",
    "get_team_limit",
    "has_permission",
    "is_custom_plan",
    "is_enterprise_plan",
    "is_evaluation_active",
    "is_paid_plan",
    "is_trial_active",
    "is_valid_plan",
    "normalize_plan",
    "plan_allows_feature",
    "require_permission",
    "timedelta",
    "timezone",
    "trial_days_remaining",

]
